### ISSUE TITLE
Dynamically start/stop row move feature

### ISSUE THREAD

**Issue by SMarongui** [ghiscoding/Angular-Slickgrid#1019]
### Clear and concise description of the problem

As of today Row Move feature is enable in gridOption with (for example)
      enableRowMoveManager: true,
      rowMoveManager: {
        singleRowMove: true,
        disableRowSelection: true,
        cancelEditOnDrag: true,
        hideRowMoveShadow: false,
        width: 30,
        onBeforeMoveRows: this.onBeforeMoveRow.bind(this),
        onMoveRows: this.onMoveRows.bind(this),
        columnIndexPosition: 0,

And Burger buttons appear at the beginning of each line to drag lines up down

### Suggested solution

Would it be possible to add the capability to dynamically switch off/on the feature once the grid is created and live.
To be able for example to 
- "enter an edit mode", showing burger buttons and enabling the drops
- "leave the edit mode", hidding the buttons and keep a static grid

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
You probably can't disable/re-enable the Row Move because it needs to be created before the grid gets created. However, you can probably hide the feature, with the override

https://github.com/ghiscoding/Angular-Slickgrid/blob/af58ea10051e9826d0593ae13c27268208345265/src/app/examples/grid-rowmove.component.ts#L104-L106

and you could also maybe hide the column
```ts
angularGrid.gridService.hideColumnById('_move');
```
apart from that, I won't change anything, that's the only option you have and that should be enough

Also please think about posting questions on Stack Overflow which is a better platform
