### ISSUE TITLE
Auto edit is not functioning

### ISSUE THREAD

**Issue by roopeshkurian** [ghiscoding/Angular-Slickgrid#1103]
### Describe the bug

Thank you for providing a wonderful and easy grid system. After upgrading to the latest version I found an issue. 
autoEdit functionality is not working. 
You can see it from the Editors example page.
https://ghiscoding.github.io/Angular-Slickgrid/#/editor

### Reproduction

Please visit https://ghiscoding.github.io/Angular-Slickgrid/#/editor  
then click Task 0 under the 'Title, Custom Editor' header. Then try to change the value.  Then when we move to another cell old edited value is replaced with the old value. 

### Expectation

When we type new values and move to another cell, it should retain the newly entered values. 

### Environment Info

```shell
Angular 15.1.5
Angular-Slickgrid 5.5.1
TypeScript 4.9.5
Browser Mozilla 110
OS windows.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
I'm not sure what you mean, I can't reproduce what you're described, it seems to be working fine on my side. Perhaps you can provide an animated gif of your problem? I use [ShareX](https://getsharex.com/) on Windows to create animated gif

Note that the main difference with `autoCommitEdit` is that it was a grid option that only existed in Angular-Slickgrid and it wasn't in the SlickGrid core lib. What I did was to add `autoCommitEdit` directly in the core lib, in this [PR](https://github.com/6pac/SlickGrid/pull/725) and this [commit](https://github.com/ghiscoding/slickgrid-universal/pull/901/files#diff-0e0411ccac9da7235fd2df966ea98f5eb9fabc917983b1c1da83cae5319d301d), now that it's part of the core lib, I no longer need to patch it in Angular-Slickgrid (actually in Slickgrid-Universal) and the patch was that it was navigating to the next bottom cell and I was forcing a re-navigate to the same cell position, now that it's in the core we no longer need to reforce a cell navigation since we aren't moving cell at all anymore when `autoCommitEdit` is enabled in the core.

![brave_brqXtXZ0aK](https://user-images.githubusercontent.com/643976/220809663-d158a538-f938-4a7e-bfd6-169c45b43395.gif)

**Comment by roopeshkurian** [comment]
In my local project, it does not work. So I thought of checking the Demo you uploaded. It does work for me there also. Can you please see the below gif?  I will try in my code again. 

![grid](https://user-images.githubusercontent.com/15811922/220813713-29fe8db8-22b5-4460-84a0-b116885d6723.gif)

**Comment by ghiscoding** [comment]
I need a way to replicate the issue or else I'm afraid that I can't do much in troubleshooting the issue. Have you tried clearing your cache maybe? Also I assume that you know that the `autoCommitEdit` isn't enabled by default (neither is in the demo and neither is in the animated gif that you provided, you must click the checkbox "Auto Commit Edit" for it to be enabled).

**Comment by roopeshkurian** [comment]
I found that, After changing values, if I use TAB or 'Enter' key the value gets changed. But If I use the mouse to navigate to the next cell value is not updating.

**Comment by ghiscoding** [comment]
ok I see now, I'm able to reproduce and I'll see what I can do in the next few days to fix this since it's quite a bug indeed. Thanks for the reproduction. Strangely it doesn't have that problem in Slickgrid-Universal itself, but I see the same bug in Aurelia-Slickgrid.

**Comment by ghiscoding** [comment]
@roopeshkurian thanks for reporting this and providing ways to replicate, it was a hard one to fix and it took a lot of troubleshooting and digging. The new release [v5.6.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v5.6.0) should resolve all issues, make sure to also update any Slickgrid-Universal dependency you might have. Cheers ⭐

**Comment by roopeshkurian** [comment]
Thank you so much for solving it.  Like always you were so prompt to address this issue and solve it.   It was a great help.  Once again thank you :-)

**Comment by ghiscoding** [comment]
Welcome thanks for using the lib 😉 🎉
