### ISSUE TITLE
Tree scrolls and flickers on frequent update on tree data

### ISSUE THREAD

**Issue by kiranbangar5946** [ghiscoding/Angular-Slickgrid#1201]
### Clear and concise description of the problem

We have tree with 3 levels, it work great.Thanks. But when at level 3 there are multiple updates the ui flickers and if user wants to see it scrolling , unable to scroll as scroll moved up and down due to updates. Please suggest and help.

### Suggested solution

Child fluctuation stops.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
unless you provide a full way to reproduce I cannot help

**Comment by kiranbangar5946** [comment]
1. Create 3 levels in tree. a. Grandparent b. parent c. child
2. Insert atleast 50-100 childs after every second or less for that heirarchy.
3. We will observe , if user wants to scroll and see the data added at bottom .It wont allow to navigate bottom ,as scroll moves to top every time a new child is inserted. I guess on new row insert scroll is forced to move to top.Which makes it difficult to see child added which is at bottom .
Only way to see the child added are once all the childs are inserted and dom is no more manipulated.

Thanks in advance.

**Comment by ghiscoding** [comment]
I assume you were using the GridService `addItems`, the default behavior of that method was to scroll top by default (which was dependent to the `position` option). I removed the default `position` scrolling and also added `scrollRowIntoView` option to `addItem(s)`, this new option is true by default and will scroll to the inserted item instead of scrolling to top or bottom, you could also disable that new option and if you do then it will insert in the grid but without scrolling anywhere

So was released under [v6.1.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v6.1.0)
Cheers ⭐

**Comment by ghiscoding** [comment]
I'm not sure if the problem was occurring with a Tree Data Parent/Child or a Hierarchical Tree but a fix was also pushed to fix an issue that was scrolling back to top when inserting a new item. In summary, a scrolling to top for Tree Parent/Child was fixed in v6.1.0 and similar problem was fixed for Tree Data Hierarchical in v6.2.0

You can test insert in both examples
- [Example 28](https://ghiscoding.github.io/Angular-Slickgrid/#/tree-data-parent-child)
- [Example 29](https://ghiscoding.github.io/Angular-Slickgrid/#/tree-data-hierarchical)
