### ISSUE TITLE
It doesn't work in angular 6

### ISSUE THREAD

**Issue by t-zander** [ghiscoding/Angular-Slickgrid#121]
**I'm submitting a bug report**

* **Angular Version:**
major.minor.patch
6
* **Library Version:**
major.minor.patch

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript X.X

**Current behavior:**
I got a bunch of errors like these: 

> node_modules/angular-slickgrid/app/modules/angular-slickgrid/filter-conditions/index.d.ts(2,36): error TS1003: Identifier expected.
> node_modules/angular-slickgrid/app/modules/angular-slickgrid/filter-conditions/index.d.ts(2,74): error TS1005: ';' expected.
> node_modules/angular-slickgrid/app/modules/angular-slickgrid/filter-conditions/index.d.ts(3,26): error TS1005: ';' expected.
> node_modules/angular-slickgrid/app/modules/angular-slickgrid/filter-conditions/index.d.ts(3,27): error TS1003: Identifier expected.
> node_modules/angular-slickgrid/app/modules/angular-slickgrid/filter-conditions/index.d.ts(3,65): error TS1005: ';' expected.
> node_modules/angular-slickgrid/app/modules/angular-slickgrid/filter-conditions/index.d.ts(4,35): error TS1005: ';' expected.
> node_modules/angular-slickgrid/app/modules/angular-slickgrid/filter-conditions/index.d.ts(4,36): error TS1003: Identifier expected.

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by ghiscoding** [comment]
The README on first page does mention the following

> Angular Compatibility
version 1.x.x for Angular 4 to 6 (*ng6, need rxjs-compat as shown in this [post](https://github.com/ghiscoding/Angular-Slickgrid/issues/36#issuecomment-395710915))
version 2.x.x for Angular 7+

I assume that you did not see this mention and I assume you tried using the latest version (I cannot see which version you use since you didn't put it in the issue) of the grid `2.1.x` but that won't work as the README was saying. If you still want to use Angular 6, you will need to use the library version `1.x` and use `RxJs compat` like mentioned in this [post](https://github.com/ghiscoding/Angular-Slickgrid/issues/36#issuecomment-395710915)

**Comment by ghiscoding** [comment]
@t-zander 
Have you got it to work? I'm tempted to close the ticket since I know it was working for lot of folks the provided [post](https://github.com/ghiscoding/Angular-Slickgrid/issues/36#issuecomment-395710915). However I strongly suggest to upgrade to Angular 7 to get latest features of the lib

**Comment by t-zander** [comment]
Yes please close the issue, it's okay. Sorry for disturbing.

**Comment by ghiscoding** [comment]
No worries, thanks for the feedback. 
You can also up vote if you like the lib ⭐️ 

Thanks for using it 😃
