### ISSUE TITLE
The Multi-column tri-state sorting option doesn't work

### ISSUE THREAD

**Issue by CAHOCA** [ghiscoding/Angular-Slickgrid#1215]
### Describe the bug

When attempting to enable the tri-state multi-column sorting option to reset its original order, it is not functioning as expected. Specifically, an error is generated from the JS file of the library, even after setting the `tristateMultiColumnSort` property to `true` in the `GridOptions` object. 

This issue is not specific to my project since I encountered the same problem in the example project I cloned from https://github.com/ghiscoding/angular-slickgrid-demos. It is possible that I am forgetting something about it, but I have not found a solution to this specific problem.

![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/43701590/1f7fa48c-0517-4f28-9357-336794db0d78)

### Reproduction

The bug can be reproduced in `GridBasicComponent` from the demo repository: https://github.com/ghiscoding/angular-slickgrid-demos/blob/master/bootstrap4-demo-with-locales/src/app/examples/grid-basic.component.ts

1. Inside the `'gidOptions1'` object, add the property `tristateMultiColumnSort`.
2. Set the value of this property to `true` and save changes.
![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/43701590/0dd376dc-1237-488a-87f0-6799f661f6dd)

4. Now, in the browser with this page loades. Click on any column header for the third time to trigger the tri-state multi-column sorting.
5. Observe that the error occurs when attempting to reset the original order of the sorting after the third click on the multi-column header. (Video)

https://github.com/ghiscoding/Angular-Slickgrid/assets/43701590/fd4dbd16-edd4-4b36-9215-b5a49c3f1e9b

### Environment Info

```shell
- Angular version 15.2.9
- Angular-Slickgrid version 5.6.4
- Bootstrap version 4.6.2
- Google Chrome browser version 115.0
- macOS Ventura 13.4

-On Windows and Linux environments, the issue is also displayed.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
pushing a fix in Slickgrid-Universal [PR 1059](https://github.com/ghiscoding/slickgrid-universal/pull/1059) but that fix will only be provided on Angular-Slickgrid 6.x since I do not provide support for older versions. 

However, I think you misunderstood or are misusing the feature... if we go on this original SlickGrid [Example - TriState & Numbered Sort](http://6pac.github.io/SlickGrid/examples/example-multi-column-tristate-numbered-sort.html), the description says that the `tristateMultiColumnSort` is only meant to be used as a way to do multi-columns sort but without the need to hold the Shift key. However the `tristateMultiColumnSort` should always be used in combo with `multiColumnSort`, but in your use case you are disabling it, so I don't understand why you are disabling it? Perhaps you didn't know that the multi-sort is enabled by default in Angular-Slickgrid, and you simply need to hold the Shift key to do multi-column sorting, if however you are not holding the Shift key then clicking on another column will reset the previous sort and only use the new column sort (so I typically hold Shift key to multi-sort and stop holding Shift key when I want to reset the sort). The other side note is that if you use the Column Header Menu, then you do not need to hold Shift key, it will do multi-columns sort by default (so it's basically similar to `tristateMultiColumnSort` but via a menu).
