### ISSUE TITLE
Question - removing overflow/vertical scrolling

### ISSUE THREAD

**Issue by logycon** [ghiscoding/Angular-Slickgrid#122]
Is there a way to override css/scss to change grid rendering to not to have overflow/vertical scroll, i.e. to long page format?

**Comment by ghiscoding** [comment]
I am not sure and that seems to be more of a Stack Overflow question

**Comment by ghiscoding** [comment]
Reading your question again and I'm still not sure what you meant. This library is a Grid, so why would you want to remove the overflow scrolling? Are you talking about making it `overflow-y: hidden`? 

There is a variable that I enabled by default (from the core lib), which will always show the vertical scrolling, that is to fix a problem with the Grid Menu (aka hamburger menu). If you wish to disable it, the Grid Options is `alwaysShowVerticalScroll: false`. There's also another similar variable for the horizontal, `alwaysAllowHorizontalScroll`. You might also want to make sure not to add the Grid Option `autoResize` since I assume you want the scrolling of the browser only.

If this is still not what you are looking for, then the last option you have is to possibly override any of the CSS styling with the `!important` but as you can imagine, this should be the last resource.

**Comment by ghiscoding** [comment]
@logycon 
If this answers your question, could you please close the issue. If not please provide more info and/or print screen of what you are looking for. 

If you like the lib, you can also up vote ⭐️ 
Cheers
