### ISSUE TITLE
Is it possible to prevent immediately filtering column?

### ISSUE THREAD

**Issue by wazzazz** [ghiscoding/Angular-Slickgrid#127]
Hi!
The filter triggers on each typed char, how can i fire this event by Enter key or clicking on custom button?

**Comment by ghiscoding** [comment]
This is by design and I suggest to create your own Custom Filter and configure it the way you want. See the [example](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/custom-inputFilter.ts) and the [Custom Filter - Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Custom-Filter)

**Comment by ghiscoding** [comment]
did that answered your question? if so, can we close the issue?

**Comment by wazzazz** [comment]
Yes, thanks.
