### ISSUE TITLE
Pagination component is displayed even "gridOptions.enablePagination=false"

### ISSUE THREAD

**Issue by sabeurch** [ghiscoding/Angular-Slickgrid#13]
I wanted to create my own pagination component, so I set properties as follow:
```
enablePagination: false,
backendServiceApi: {
          service: this.myDataService,
          preProcess: () => this.displaySpinner(true),
          process: (query) => this.getCustomerApiCall(query),
          postProcess: (response) => {
            console.log(response);
            this.displaySpinner(false);
            this.getCustomerCallback(response);
          }
}
```

What happens, I was able to use my pagination component, however the internal `"<slick-pagination>..</slick-pagination>"` remains displayed.
Looking into source code of version 0.10.0, I found that :
```
if (this._gridOptions.enablePagination || this._gridOptions.backendServiceApi) {
        this.showPagination = true;
```
around line #296 on file angular-slickgrid.component.ts

This will force the pagination to be displayed.

Would it be possible to allow an accessor method or adding a new boolean option to allow not to show the slick-pagination component?
The the previous condition will look like (Option 1):
```
if (!this._gridOptions.hidePagination && (this._gridOptions.enablePagination || this._gridOptions.backendServiceApi)) {
        this.showPagination = true;
...
```
Or simply (Option 2):
Change 
```
if (this._gridOptions.enablePagination || this._gridOptions.backendServiceApi) {
        this.showPagination = true;
```
Into 
```
if (this._gridOptions.enablePagination) {
        this.showPagination = true;
```

Unless there is a reason for doing that.

Many thanks in advance.

**Comment by ghiscoding** [comment]
I'll take a look at it next week, I'm working on another upcoming feature. 

I made it True when using Backend Service API so that I don't have to always define the property. I guess that I forgot to test it when using the API since I always want, in my case, to show the pagination. It's a little oversight but I do still want it enable when using the API **unless** the user define to False, which is your case. I'll try to make it without a new flag but we'll see when I get there. 

I'm just curious about your Pagination design, could you share your design? I'm not exactly crazy about how mine looks like, I'd be happy to have improvement on that side. 

Also curious, which Backend Service are you using? I thought I was the only one using it, it's nice to know others do use them :)

**Comment by sabeurch** [comment]
Dear Ghislan, 
Thank you for this quick reply.
The pagination design is similar to yours except, it adds the text input field for the page number to allow typing it manually. 
This is useful so that if I have 20 pages in total, I do not have to click for data 10 times to go into page #10. A spinner that indicates processing is added to the end (designated as {S} ).

> [<<] [< ] Page [10] of 20 [ >] [>>] {S}

Also notice that the pagination component is separate from datagrid, so it can be inserted at any place of the screen.
The design is done that way, because I am working in an old project totally written in Flex. Now we are migrating it into HTML5 via Angular and other 3rd parties.
The backend service is in fact implementing the pagination, sorting and filtering in database side. 
So, I have to send request parameter like `All|All|myfilter|All|All` if I want to filter the 3rd column with value "myfilter". A sort parameter is sent like `2|true` , this means data will be retrieved from DB being sorted based on 2nd column ASC. As for pagination, page number example 10 is sent as a request parameter.

**Comment by ghiscoding** [comment]
I would be happy to receive a PR with those changes, being able to swap which pagination component to use could also be nice. 

So if I understand correctly, you actually use a custom backend service with the API? That's cool, I made it modular but didn't think it would work right away with custom ones. But I guess it's not surprising, you just have to follow the same interface as my 2 services. Pretty cool.

**Comment by ghiscoding** [comment]
I have a fix in the queue for the next version release, but I would like write again that I would be happy to receive a contribution for the pagination. I think the pagination component I have done could receive some love and I would be happy to have the page change too by a page number. 

Would you be able to contribute? That would be really great. Thanks

**Comment by sabeurch** [comment]
Hi Ghislan, 
Sorry for the late reply.
Yes with pleasure, but the problem with our pagination component it is very stick to the Oracle DB stored procedures and I don't think it could be generic.
For the service, I started from GridOdataService and making it constructing Urls as described in my last comment.
I'll send the code once being ready (as actually I took only few hours in the day to work on it, the rest of time is for supporting customers).

**Comment by ghiscoding** [comment]
The fix is for this is part of the new [version 0.11.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v0.11.0)

It still uses the same flag `enablePagination` but I removed it from my [global default options](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/global-grid-options.ts) which means that it is now an `undefined` property. The new logic in the Angular-Slickgrid component is still seeing if you are using the Backend Service API and if you do and the flag is `undefined`, it will consider that it should display the Pagination Component, however if it is set to `False`, it won't show the Pagination. Basically I cheat it a bit, I use a boolean as a 3 states flag (true/false/undefined) and it works :)

Thanks for reporting and please provide your Pagination example and/or make contributions. I would like to also be able to change the page number on my side too.
