### ISSUE TITLE
Bug: Using enableFiltering with enableTranslate and disabling showHeaderRow

### ISSUE THREAD

**Issue by melvinvdb** [ghiscoding/Angular-Slickgrid#144]
**I'm submitting a bug report**

* **Angular Version:**
7.2.7

* **Library Version:**
2.4.1

* **Browser:**
all

* **Language:**
TypeScript 3.2

**Current behavior:**
This might be a bug in Slickgrid not Angular-Slickgrid but I'm unsure.
The filter header row isn't created with the following configuration:
- enableFiltering: true
- showHeaderRow: false
- enableTranslate: true

**Expected/desired behavior:**
I expect to not see a filter header row when loaded. When 'toggle filter row' is pressed I expect to see the filters sliding down but none are shown (a blank div slides in though).
In Chrome inspector you can see that none of the filters are created (the div is empty).
Check the clientside example and set `showHeaderRow` to false and also set `enableTranslate` true to reproduce this issue.

**Comment by ghiscoding** [comment]
I had issues with that too in our project, I wanted to not show the Filters at first but make it available through the Grid Menu. But as you found out, you can't disable `showHeaderRow` since it won't create the Filters, the reason is because the lib uses `onHeaderRowCellRendered` to know when to create the Filter and if you disable the row then it never triggers. What you could possible do is to use a `setTimeout` to toggle the Filter row, that would probably work.

**Comment by melvinvdb** [comment]
Yes I just tried that with a timeout of 1ms. That seems to work for now. Thanks!

**Comment by ghiscoding** [comment]
I would rather close this issue then, there isn't much the lib can do to fix this other than the `setTimeout` patch

**Comment by melvinvdb** [comment]
Yes I agree.
