### ISSUE TITLE
Editor singleSelect with collectionAsync not work's

### ISSUE THREAD

**Issue by dzurrahman** [ghiscoding/Angular-Slickgrid#1470]
### Describe the bug

im just upgrade version angular from 16 to 18, and upgrade angular-slick grid into latest version,

singleSelect dropdown item wont works with collectionAsync item's

![image](https://github.com/user-attachments/assets/6cbdba82-0032-4813-afd8-d871437f9fd3)

only work's with basic collection

![image](https://github.com/user-attachments/assets/47221084-59d3-4d72-badb-9617f82daded)

here's my code with collectionAsync 

![image](https://github.com/user-attachments/assets/816f0f6e-d0f0-4b31-9cb3-a94786e2b690)

### Reproduction

-

### Expectation

should be show the list 

### Environment Info

```shell
"@angular/animations": "18.1.2",
"@angular/cdk": "18.1.2",
"@angular/common": "18.1.2",
"@angular/compiler": "18.1.2",
"@angular/core": "18.1.2",
"@angular/forms": "18.1.2",
"@angular/platform-browser": "18.1.2",
"@angular/platform-browser-dynamic": "18.1.2",
"@angular/router": "18.1.2",
"@ionic/angular": "8.2.6",
"@ionic/core": "8.2.6",
"angular-slickgrid": "8.6.1"
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [x] Read the [HOWTO - Quick Start](https://ghiscoding.gitbook.io/angular-slickgrid/getting-started/quick-start).
- [x] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zewa666** [comment]
can you show what the collection variable is?

**Comment by dzurrahman** [comment]
collection is observable, for example i used `of` from rxjs

```
of([
    { value: 'Y', label: 'Yes' },
    { value: 'N', label: 'No' },
  ]);
```

**Comment by dzurrahman** [comment]
ah, that's the problem, collectionAsync no longer compatible with Observable, thanks @zewa666 .

**Comment by ghiscoding** [comment]
`collectionAsync` always supported Promise & Observable, Example 3 has it connected a `http.fetch` which is an Observable and it works fine. I have many projects to support and not all frameworks have Observable, so it's probably just a matter of updating the docs to say it does support both Promise & Observable. If you have any problems with `collectionAsync` and Observable, you need to provide a full repro there's a Stackblitz link on the main readme homepage, otherwise I won't help.

https://github.com/ghiscoding/Angular-Slickgrid/blob/5613f28f736acca90b8597097b48c6e0b9f9b802/src/app/examples/grid-composite-editor.component.ts#L312-L329

and here's the unit test for this feature

https://github.com/ghiscoding/Angular-Slickgrid/blob/5613f28f736acca90b8597097b48c6e0b9f9b802/src/app/modules/angular-slickgrid/components/__tests__/angular-slickgrid.component.spec.ts#L773-L786

**Comment by ghiscoding** [comment]
I came back and tested `collectionAsync` with an `of` Observable and it works fine, so as I mentioned above, just make sure that the input is in fact not null or undefined when reading the column definitions. 

```ts
filter: {
  model: Filters.singleSelect,
  enableCollectionWatch: true,
  customStructure: { value: 'value', label: 'label' },
  collectionAsync: of([
    { value: 'Y', label: 'Yes' },
    { value: 'N', label: 'No' },
  ])
}
```

There's also a couple of things that I'd like to mention after seeing the code you provided
1. an `editor` can only accept a `filterOptions` and seeing that you also provided `editorOptions` is wrong
2. the option `customStructure` should only be used when you want to override it with something **other than** value/label, you are overriding it with the default, so there's no need to provide it in your case
3. `type: FieldType.text` is the default, so there's also no need to provide that one either
4. your function `getDropdownConfig` should really return a `Column` type which would have detected the error 1 above



![image](https://github.com/user-attachments/assets/5fcc0e3d-26b5-4e40-9aa3-0c8f464f11fe)
