### ISSUE TITLE
Inline Form , footer detail , Array Base data display

### ISSUE THREAD

**Issue by kamlesh0606** [ghiscoding/Angular-Slickgrid#148]
Hi,

I have Some query in this api.

1. Can i make inline Form (Ref. Point 1 in photo) ?

2. Can i Show footer detail Like Total Records and other think (Ref. Point 2 in photo)?

3. Can I export inline From Data Like Textbox Value?

4. Can I display Array inside Array Data to column ( This case column data base on array index Or Array Key ) (Ref. Point 3 in photo) ?

![as-1](https://user-images.githubusercontent.com/3240948/54082533-238cb200-433d-11e9-8e4e-6785ced852ca.jpg)

Thanks

**Comment by ghiscoding** [comment]
I think that you should take a look at the core lib SlickGrid [examples](https://github.com/6pac/SlickGrid/wiki/Examples), if what you want is in there then it's probably doable in Angular-Slickgrid. Also just as a reminder, Angular-Slickgrid is a wrapper of SlickGrid (a jQuery datagrid). 

1. There's no Pagination available for regular grid (with JSON dataset), I only added it with a Backend Services (GraphQL/Odata). I added a small Statistic property but it's very limited, you can see it on top of the grid in this [Example](https://ghiscoding.github.io/Angular-Slickgrid/#/clientside). 
2. There's a footer available in SlickGrid (core lib) but I never used it, so I'm not sure how much work it would be to add that piece.
3. Not sure what you mean exactly but you can export anywhere from a button as can be seen in this [Example](https://ghiscoding.github.io/Angular-Slickgrid/#/localization). You can have a Custom Formatter that has a button to export. 
4. Again not sure what you mean

Just as a reminder, this is an Open Source project and I'm the main person who did most of the work but that is a lot of work for 1 person, if you can contribute to this project I would be really happy. Please look at all the examples available in this lib and in the core lib, if you can't find what you're looking then perhaps it's not available. There's also Stack Overflow that can answer some of your questions.

**Comment by kamlesh0606** [comment]
Thanks for give reply,

I tried for help in this project. i looking all demo and setting for my company new project. if any missing then i will do it in your project.

For point 4 , dynamical add column base on setting Or Http ws respond.   

Thanks

**Comment by ghiscoding** [comment]
You can dynamically add a Column by adding a Column Definition object to the array of Columns and you can see that in this [Example](https://github.com/Microsoft/vscode/issues/45693) but that is a manual process, you cannot do that based on a column variable since that is way too advanced and is more of something you can find in paid grid like maybe `ag-grid`. 

For point 1 shown in the picture, that should be doable with a Custom Formatter to just display it in a different way (just remember that a Formatter must be a string that can contain HTML). You can also work with complex objects, it will use the dot "." notation (in the `field` property) to know how to use it. You can see a complex object in this [Example](https://ghiscoding.github.io/Angular-Slickgrid/#/clientside) where the Effort Driven column is a complex object as defined [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-clientside.component.ts#L130). You can also use Custom Formatter to display something different according to certain logic, for example if the result is over 90 then display A+.

**Comment by ghiscoding** [comment]
@kamlesh0606 
Since these all seems like questions and not really an issue with the lib, can I close this issue?

**Comment by kamlesh0606** [comment]
Thanks for your support .

**Comment by kamlesh0606** [comment]
Hi,
Can i use '**ngModel**' with textbox Or checkbox ?

I used Custom formatter with return following html.
`<input type="checkbox" class="form-control-checkbox" [(ngModel)]="studentToBePaidDetail.isChecked" (change)="selecteOnecheckbox($event, studentToBePaidDetail)">`


Can i use angular type code Like 2 way mapping , .... ?

Thanks

**Comment by ghiscoding** [comment]
All the info for your question is in this previous [release](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.3.3) that was done recently. The answer is "Not with Custom Formatters" but you can use `asyncPostRender` but that has some drawback. That is an async method (like the name suggest) and are **not** rendered right away and you might see that rendering happening. So it's better to use Formatters because they are rendered instantly (not async), but those only accept String (with/without html tags). Personally I will most probably never use the `asyncPostRender` and will stick with Customer Formatter (even if it mean using only plain string/html). 

Also note that the limitation that a Custom Formatters only accepts String comes from the core lib (SlickGrid) and there's nothing Angular-Slickgrid can change about that, the only alternative, like I said earlier, is to use `asyncPostRender` with it's drawback (it's slightly slower to render). 

Added that to the [Wiki - Formatters](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#using-angular-component-with-asyncpostrenderer)

**Comment by kamlesh0606** [comment]
Got your point. Like Take some time , at that time display '...' in column then display data.

Thanks for it.
