### ISSUE TITLE
Not deleting item when id is changed in DataGrid

### ISSUE THREAD

**Issue by KumVishal** [ghiscoding/Angular-Slickgrid#149]
**I'm submitting a bug report**

* **Angular Version:**
Angular 7

* **Library Version:**
2.4.2

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript 3.2.2

**Current behavior:**
The datagrid is throwing error for the items whose id has been changed while deleting those items.

**Expected/desired behavior:**
The datagrid should delete the items whose id has been changed.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
. The user created the item.I add it immediately on client side with a temporary unique ID.
. I query the server to get the unique id for that item.
.Then I update that item with the server side id.
.Then I call angularGrid.gridService.updateDataGridItem(item);
. Now I want to remove that item from the grid.

**Comment by ghiscoding** [comment]
You might not be using the correct update method, the thing is that the DataView object (which holds the entire dataset and is part of the core lib) needs to update its dataset internally, else it won't be able to delete if the DataView doesn't have latest items with updated Ids. 

From the look of your question, you're using `updateDataGridItem` but that won't work, , the method goes and find the id within the item object by itself, but if you use that with a new object then it won't find it in the dataset because you just brought a new id and DataView doesn't know anything about it. I think you should be using `updateDataGridItemById(oldId, newItemObject)` instead. It would help to troubleshoot if you attach the entire error. 

I have a feeling that you'll get more answers on Stack Overflow, this seems to be more of a core lib issue and howto. I don't think there's anything wrong with Angular-Slickgrid itself.

**Comment by KumVishal** [comment]
Hi @ghiscoding ,

Thanks for the information. I tried as suggested by you but I am getting the following error after I use updateDataGridItemById(oldId, newItemObject).

"Error: Invalid or non-matching id\n    at DataView.updateItem"

Is there any way, through which I can delete an item after I update that "item id" with the id fetched from the server response.

Thanks.

**Comment by ghiscoding** [comment]
So the error that you shown comes from the DataView core lib, from this [line](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js#L360). After some googling for your use case, I found this Stack Overflow [question](https://stackoverflow.com/questions/31070181/slickgrid-how-to-modify-id-value) and the guy says that he has problem as well updating an object id. In the answer we can see he wrote the following

> So, I guess I hadn't quite grasped how the data view is disconnected from the grid. So I decided to store the key field twice in there once as a (non editable) Id field and once as an editable name field.

This makes me realize that yes Angular-Slickgrid also does use the DataView and the Grid. These are 2 different classes available in Slickgrid and they do different things. I use the DataView because of all the functionality that it brings (built-in multi-column sorting, multi-column grouping, etc...). So all that to say that the person mention there's a sync issue between the Grid & DataView classes, I don't fully understand his answer and don't have time to investigate more at this time. 

What I would suggest you is instead of using `updateDataGridItemById` (which is just a utility method using the core lib methods). Go get the SlickGrid and DataView instances directly (you can get them with `angularGridCreate`, more info in this [Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-&-DataView-Events#example-with-onangulargridcreated-event-emitter)) and then copy the code from `updateDataGridItemById` with the code [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/grid.service.ts#L454) and try to modify it according to the Stack Overflow [answer](https://stackoverflow.com/a/31111982/1212166) provided. Once you get the code working, we can update the `updateDataGridItemById` method with the necessary code change.

**Comment by ghiscoding** [comment]
Actually, I just found out that it's not currently possible as can be seen in this [issue](https://github.com/mleibman/SlickGrid/issues/1082) but if you scroll down the issue, you can see a [fix](https://github.com/GerHobbelt/SlickGrid/commit/d157fd7ec55482e3e7f5990e5bf46aedf65371da) that got pushed to another fork of SlickGrid. So the current version of the SlickGrid DataView is going to block you from doing an `id` change. The best I can do is maybe ask the 6pac fork (the one my wrapper is using), if we can get this fix to be ported over to 6pac/slickgrid as well.

**Comment by KumVishal** [comment]
Hi @ghiscoding ,

Thanks for the update. It would be of great help if you could ask the 6pac fork to have a fix for this.

-Regads
Vishal Kumar

**Comment by ghiscoding** [comment]
I can ask but in the mean time what you could do is possibly use another column to be your ID, as long as it's a unique ID and that's not something that will change. Basically, you can use [datasetIdPropertyName](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/gridOption.interface.ts#L97) to use a different column as the ID used by the DataView, but again it has to be unique and never change, since this is the problem you have now. I'm not sure if you do have that but it would be a way to continue working

**Comment by ghiscoding** [comment]
The fix with PR [#354](https://github.com/6pac/SlickGrid/pull/354) on the core lib has been pushed and merged. It should take a week or 2 before seeing a new release and then it will become available in Angular-Slickgrid. I'll leave the issue open until then.

Also if you like the lib, you can also up vote ⭐️ if you haven't already. 
Thanks

**Comment by ghiscoding** [comment]
This should be fixed with latest version [2.4.4](https://www.npmjs.com/package/angular-slickgrid)

**Comment by KumVishal** [comment]
Hi @ghiscoding 

I have updated the package to 2.4.8 and found that the issue still persists.
I am getting the error ""Error: Invalid id\n    at DataView.deleteItem" when performed the same steps as mentioned above.

**Comment by ghiscoding** [comment]
When I tried it was working for me, so unless you provide a full example I cannot really help. You will have to troubleshoot the code of slickgrid I guess. The code change in the core lib came from this [post](https://github.com/mleibman/SlickGrid/issues/1082) which describes exactly what you are/were trying to achieve and it worked when I tried it. 

The error that you are getting is coming from this [line](https://github.com/6pac/SlickGrid/pull/354/files#diff-c304fa0a9fc10aec37c9ce9369bd0be8R361) of the core lib and if you fall on this line, it's usually because you are providing an object or an id that is not at all in your dataset, you have to remember to use your original temp id so that you can find the row/object and it looks like you are not.
