### ISSUE TITLE
Dropdown in Column

### ISSUE THREAD

**Issue by ananddotnetdeveloper** [ghiscoding/Angular-Slickgrid#152]
Hi, 
Using editor i can create a custom Dropdown, but its  showing as a dropdown after user clicks on the particular cell , but i need to show it as a drop drown by default and change. 

Here Assigne column is a dropdown , but its not looking like that unless user clicks on that 

![image](https://user-images.githubusercontent.com/21267441/54622956-f62cbc00-4a40-11e9-9ded-322bc8d3c04d.png)

![image](https://user-images.githubusercontent.com/21267441/54622988-0349ab00-4a41-11e9-91ee-58ca261443e7.png)

**I'm submitting a feature request**

* **Angular Version:**
7

* **Browser:**
all 

* **Language:**
TypeScript 3.3

**Current behavior:**

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by ghiscoding** [comment]
That is expected and is by design, SlickGrid (the core library) expect a cell text, you can use a Formatter but again it expects a string (with/without HTML). Why would you want to display a dropdown that is not an editor? Are you looking into doing a certain action depending on the value chosen from the dropdown? I don't really understand what you're trying to do... perhaps you could try the `asyncPostRender` mentioned in an earlier lib [version](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.3.3) and the [Wiki - asyncPostRender](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#using-angular-component-with-asyncpostrenderer)

**Comment by ananddotnetdeveloper** [comment]
yes i am looking to do some action based on the value selected in the drop down

**Comment by ghiscoding** [comment]
If you're looking into using Angular Component for that, you'll have no choice but to use `asyncPostRender`, see what I wrote in previous post, and make it an Angular Component that is a dropdown. I don't see other ways of doing it. 

On a side note, if you just wanted to do something when user click on an icon or a cell, you could use the `onCellClick` event which you can see in the [Example 3](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) the first column has 2 buttons to delete/edit and it uses `onCellClick`. It's not exactly what you're trying to do, but in some cases it might enough.

**Comment by ananddotnetdeveloper** [comment]
Do we have any Example of creating and using a Angular Component

**Comment by ghiscoding** [comment]
> perhaps you could try the `asyncPostRender` mentioned in an earlier lib [version](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.3.3) and the [Wiki - asyncPostRender](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#using-angular-component-with-asyncpostrenderer)

I did answer you earlier with that... it's in the  [version](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.3.3), so go take a look there.

**Comment by ghiscoding** [comment]
@ananddotnetdeveloper 
Did that answered your questions? Can we close this issue since it's not really an issue?

**Comment by ananddotnetdeveloper** [comment]
yes we can , thank you

**Comment by ghiscoding** [comment]
Thanks
