### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by kamlesh0606** [ghiscoding/Angular-Slickgrid#156]
Hi,

Please help in 'infinite scrolling' implementation.

Thanks
kamlesh

**Comment by ghiscoding** [comment]
I don't think that SlickGrid supports infinite scrolling and so Angular-Slickgrid won't support it either since it relies on the core lib having the feature.

I must remind you that this library is an Open Source project and is provided **"as is"** as defined in the [MIT License](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/LICENSE). If you want to ask questions, I suggest you [Stack Overflow](https://stackoverflow.com).
