### ISSUE TITLE
How to add validation message on cell

### ISSUE THREAD

**Issue by loonix** [ghiscoding/Angular-Slickgrid#158]
Hi Guys,

I am taking a look at the way validation is done on Angular-SlickGrid. I was wondering if there is an option to add the validation message as a tooltip on the cell? Is this possible or already exists?

Regards,

**Comment by ghiscoding** [comment]
That seems to be more of a question that you can ask on Stack Overflow related to SlickGrid (the core lib), it's not really Angular-Slickgrid. There's 2 callback you can possibly use to work that out, `sgOnBeforeEditCell` and `sgOnValidationError`, possibly the later.

**Comment by loonix** [comment]
Thanks for the help!

**Comment by ghiscoding** [comment]
@loonix 
Taking a quick look at the code for all the Editors and I could possibly add a way to change the `title` attribute so that you can get tooltip. However some Editors, like the Float Editors has many validation checks (as can be seen [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/editors/floatEditor.ts#L186)). 

I think that just giving you access to provide your own message to the `title` attribute should be enough, don't you think? I did the same for the `placeholder` attribute, so I don't mind adding the `title` as well (as I've done in this [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/129ad61f6b0b45cfd95c8167d29d3ebb2e632153#diff-5e396cd2b57de1f4575fbdb995e43814)).

**Comment by loonix** [comment]
That sounds reasonable, and many thanks for the feature.

**Comment by ghiscoding** [comment]
This feature is now available under the latest version release [2.4.7](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.4.7)

Thanks for the feedback and up vote ⭐️  if you haven't already
Cheers
