### ISSUE TITLE
2.4.4 is breaking existing RowDetail

### ISSUE THREAD

**Issue by ananddotnetdeveloper** [ghiscoding/Angular-Slickgrid#160]
**I'm submitting a bug report**
Here is the screen shot 
![image](https://user-images.githubusercontent.com/21267441/55525262-6ef56000-565e-11e9-8203-76f64602c464.png)

Error in console
![image](https://user-images.githubusercontent.com/21267441/55525280-7caae580-565e-11e9-890c-2381dd447bb0.png)

* **Angular Version:**
7

* **Library Version:**
major.minor.patch

* **Browser:**
all 
* **Language:**
TypeScript X.X

**Current behavior:** Row detail plugin is not working with new release 

**Expected/desired behavior:** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by ghiscoding** [comment]
Right, I used latest version of `Slickgrid` but yeah there is (was) a problem in the core lib. I fixed it in this [PR](https://github.com/6pac/SlickGrid/pull/358) on core lib, but we need to wait for the next core lib release to get the fix propagate to Angular-Slickgrid lib. Not sure when that will happen, I'll ask the core lib maintainer if he could push a version in the coming weeks.

In the mean time, I suggest you to use previous version of Angular-Slickgrid, I'm also waiting for the core lib to release a new version as well so I can merge my open PRs.

**Comment by ghiscoding** [comment]
I pushed a temporary fix with version `2.4.6` of my lib, I say temporary because I change the dependency to `"slickgrid": "github:6pac/SlickGrid"` and that works if you start fresh but won't work if you have a Yarn or NPM lock file, if you do then just delete your lock file and run an NPM or Yarn install, it should pick up the latest code of SlickGrid (the core lib) which has the Row Detail fix in. 

I'm leaving this issue open because I want to address properly by using SlickGrid NPM version, we'll have to wait until the owner of the SlickGrid repo (core lib) pushes an NPM version. 

Again in the meantime, please delete your Yarn/NPM lock file and reinstall, you should be good to go. I did that to rebuild the [Row Detail - Example](https://ghiscoding.github.io/Angular-Slickgrid/#/rowdetail) and it's all fine now.

**Comment by ghiscoding** [comment]
The fix to use latest version of SlickGrid (core lib) was pushed under the PR #157 
Simply update to version Angular-Slickgrid `2.4.7`
