### ISSUE TITLE
Copy paste from excel creates additional fields

### ISSUE THREAD

**Issue by loonix** [ghiscoding/Angular-Slickgrid#164]
**I'm submitting a bug report**

* **Angular Version: ** *
7, 5

* **Browser:** *
all

**Current behavior:**
When a grid is editable and a user copies a row from excel and pastes on slickgrid it creates additional dropdowns and date pickers.

**Expected/desired behavior:**
User copies the values from excel and pastes on the grid.

* **What is the expected behavior?**
Not create those additional fields when pasted the values

![copy paste issue](https://user-images.githubusercontent.com/3384277/55864875-37624880-5b75-11e9-8600-b3dd3515e3b9.PNG)
![copy paste issue2](https://user-images.githubusercontent.com/3384277/55864978-709ab880-5b75-11e9-804e-787ef649b435.PNG)

**Comment by ghiscoding** [comment]
Hmm I never use the copy + paste feature, but have you tried pasting good values? I see all your cell are not good values with the format that they should receive. The other thing that I can see is that the dropdown `ms-filter` needs to use `container: 'body'` inside the `SelectEditor` and it might be the reason why it shows up, I'm not sure about the `DateEditor` though. 

Unfortunately I really don't have time to troubleshoot this problem since I never use it either. It would be helpful if you can troubleshoot it by downloading the lib and running it, you can debug with VSCode and Chrome Debugger that is part of the project.

**Comment by loonix** [comment]
Thanks for your answer, I tried to enable/disable autoEdit flag but the result is the same.

After checking a few scenarios the following are affected:
- datepicker
- Single/Multi select

But found that the normal text inputs and the autocomplete work well without any problems.

This might not help but I've done some debugging to see where it is generating:

Debugging the dateEditor found that this line is triggering it wrong (just not sure what):
![image](https://user-images.githubusercontent.com/3384277/55887973-7492fe80-5ba6-11e9-9f16-79cecf5f1c47.png)

Debugging the selectEditor the dropdown gets generated after this line:
![image](https://user-images.githubusercontent.com/3384277/55888624-980a7900-5ba7-11e9-9813-a2893b584c0b.png)

**Comment by ghiscoding** [comment]
You could maybe try to add a breakpoint to the other editors (like the `InputEditor`) to see if it always goes inside each editors `init()` method. If it does, then there must be a property somewhere that says, don't render the editor or something. Maybe another thing to check also, are the `DateEditor` and `SelectEditor` working fine in the grid after you click in the cell? or are they really the ones showing at the bottom associated to the line?

**Comment by loonix** [comment]
It seems that the datepicker does not recognise the `args.**item**` when it is a copied value.
![image](https://user-images.githubusercontent.com/3384277/55892793-e5d6af80-5bae-11e9-9c29-91d28dcee0a4.png)

But the item does get recognised when a value is selected from the datepicker:
![image](https://user-images.githubusercontent.com/3384277/55893015-554c9f00-5baf-11e9-93aa-2d27f4d15dd9.png)

**Comment by ghiscoding** [comment]
Sorry I don't really have time to look into this, but for a very brief look into the problem. I can replicate in the [Editor Example](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) however this feature does work in SlickGrid core repo, that can be seen in this sample is this [Excel Copy Example](http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html) which also has Editors. 

In Angular-Slickgrid, what I can see is that on top of creating extra fields at the bottom, is that it also doesn't paste any of the copied text content in any cells. Disabling `autoEdit` (which can be turned off in the [Example Editor](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) doesn't seem to help, so that is not the issue. I also tried removing the Date & Select Filters which are causing the extra fields, but again that didn't help. 

However we might have a hint of where the issue comes from, if I copy some cells from the 1st row and try to paste on the 5th row, I see the 1st row gets highlighted (because of update) and it shows the "Updated Items" (blue bootstrap alert) with info about the 1st row. So perhaps the paste does occur but not in the correct row and then there's still the issue that you mentioned earlier with the extra inputs that get created. Lastly what I can see is that the problem seems to be really around the Editors, when trying to do the same copy+paste in [Example 2 - Formatters](https://ghiscoding.github.io/Angular-Slickgrid/#/formatter) it does work, it's only when adding Editors that it stops working. Finally if I disable the Editors via `editable: false` in the Grid Options, then it works, so again pointing to an issue within the Editors.

This was just a quick look at the problem, like I said I barely have any time to investigate more than that. All I did was to replicate the issue and try to observe where the issue might be coming from. At least, we now know that SlickGrid core is ok, and also that it does work in Angular-Slickgrid without using Editors.

**Comment by ghiscoding** [comment]
I found an interesting thing though, in my Example, if I do my copy+paste from the 1st column instead of the 3rd (which mean that I include the 2 first icon columns), it does work. It adds the extra fields but it does paste the content. That is strange, since the core lib [Example](http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html) accept copy+paste from any cell location.

**Comment by ghiscoding** [comment]
@loonix 
Good news I found the issue and fixed it in my other repo (Aurelia-Slickgrid) with this [PR](https://github.com/ghiscoding/aurelia-slickgrid/pull/160). 

While troubleshooting this, I found 2 issues which are the following
1. when using the `CellExternalCopyManager` plugin and doing a copy (Ctrl+C) it calls an init on each editor but destroys them right after, I found this behavior while troubleshooting with this [SlickGrid Example](http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html). 
   - However in the case of the DateEditor and the SelectEditor, in my repo I was not correctly dealing with the Editors `show()` and `destroy()` method internally. Now it's fixed
2. Copy & Paste was not pasting at the correct cell location in the grid. 
   - The issue was that the cell was actually not in focus and we can fix when by calling `grid.setActiveCell(args.row, args.cell);` on the `onClick` event. I will do that internally in the lib, so there's nothing for you to do.

I will create a PR in Angular-Slickgrid early next week
Here's a preview of the fix 

_* note that the mouse cursor location is incorrect in the animated gif because I have a high resolution screen, kinda weird)_

![1yXlgOLuQx](https://user-images.githubusercontent.com/643976/56855646-a7fcb980-6918-11e9-8e8b-e67de8aff63b.gif)

**Comment by loonix** [comment]
I've been taking a look myself but got lost. This is amazing news! Thank you very much for this!

**Comment by ghiscoding** [comment]
Yeah that bug required a in depth understanding of how the core SlickGrid lib works.
I also found another small issue, which you can see in the animated gif on top, the paste was not pasting all values. That will be fixed as well

**Comment by ghiscoding** [comment]
Alright the fix is pushed and released under new version `2.5.3` on [NPM](https://www.npmjs.com/package/angular-slickgrid)

However, there is an important to note. One of the issue was the cell not becoming active (in focus) when you click on it, and I was going to fix that globally but then I found a side effect that prevent the Editor to save properly. So I only enable it globally (set active cell in focus) when you use Editor and have the grid option `autoCommitEdit` set to True. You can see what I mean in the animated gif below, at the beginning the checkbox "Auto Commit Edit" is not checked, and you see after I click on the cell, it's not fully in focus but then I enable the "Auto Commit Edit" and then click on the cell again and now when I click on the cell, the background color becomes a darker blue which mean it's the active cell and is in focus. Personally I always use the `autoCommitEdit` in all my grids and I suggest you do the same.

Enjoy the lib and thanks for the feedback and help in troubleshooting. 
Cheers

![2019-04-29_11-42-38](https://user-images.githubusercontent.com/643976/56908273-fe323f80-6a73-11e9-921d-b8dfdae21820.gif)
