### ISSUE TITLE
How to load items per page and total items in pagination at the bottom of the slick grid

### ISSUE THREAD

**Issue by Osmo123** [ghiscoding/Angular-Slickgrid#168]
How to assign values for item per page and total items in the grid to show the values at the right corner of the grid

* **Angular Version:**
major.minor.patch

* **Library Version:**
major.minor.patch

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript X.X

**Current behavior:**
I am getting the fields as bold letters, but I assigned pageSize and totalItemCount in post process method, but the values are not binded in the grid

**Expected/desired behavior:**
Those should be like 10 to 100 records and the lables should be as small letters. I am using Odataservice to load the data

* **What is the expected behavior?**
I don't have translate language to my website, but I need to reassign those item fields with the proper count as from the back end

* **What is the motivation / use case for changing the behavior?**
![image](https://user-images.githubusercontent.com/40761775/56219825-03ab8500-6085-11e9-962a-cd274a705278.png)

**Comment by ghiscoding** [comment]
`ngx-translate` needs to be installed and configured, even if you use only 1 language. It is mandatory and more info can be found in the [README](https://github.com/ghiscoding/Angular-Slickgrid/wiki/HOWTO---Step-by-Step#5-installsetup-ngx-translate-for-localization). The English translations are in this [file](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/assets/i18n/en.json), I believe you need to create it and load it as your default language, I don't think there's any way around it. However if you use only 1 language, you probably don't need to load them through a JSON file, you could load them in memory instead, read the [ngx-translate](https://github.com/ngx-translate/core) doc to know how to. 

Just a reminder, you are asking what seems to be mostly questions and not really issues with the lib. I try to help people by providing info and examples by I don't really have time to answer everyone's questions. I'm mostly alone on working and building this library (I am not paid to answer these questions). I did however create a lot of Wikis to help people out, the main one people should start with is the [HOWTO](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step) and if you feel the Wikis lack information or should be edited then please let me know. If you want to help make the library better, I'm totally open to receive PR (Pull Request). Thank you

**Comment by ghiscoding** [comment]
So as I mentioned in previous post, `ngx-translate` is a dependency of Angular-Slickgrid, so you have to set it up properly, The pagination uses only translation, so you will have to include them in your translation array, you can do so in your App Component (you also need to configure it in your App Module as shown in this [Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Localization#app-module)), so the minimal translation setup you need is the following (in your App Component):
```ts
translate.setTranslation('en', {
    FROM_TO_OF_TOTAL_ITEMS: "{{from}}-{{to}} of {{totalItems}} items",
    ITEMS: "Items",
    ITEMS_PER_PAGE: "items per page",
    OF: "of",
    PAGE: "Page",
    PAGE_X_OF_Y: "page {{x}} of {{y}}",
});
```
That is the minimum that you need to configure and use for the Pagination to work and be translated properly. 

As for the total items with OData, if I remember correctly (I only use GraphQL lately), you need to set the total items yourself like mentioned in this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-odata.component.ts#L106) like so
```ts
backendServiceApi: {
        service: new GridOdataService(),
        preProcess: () => this.displaySpinner(true),
        process: (query) => this.getCustomerApiCall(query),
        postProcess: (response) => {
          this.statistics = response.statistics;
          this.displaySpinner(false);

          // set `totalItems` and `totalRecordCount` might be a different property name on your side
          this.gridOptions.pagination.totalItems = response['totalRecordCount']; 
        }
      }
```

I believe that I answered your question and since this is not an issue with the lib, I will close this issue.
