### ISSUE TITLE
custom validation is not triggered when pasting data from clipboard in editor

### ISSUE THREAD

**Issue by sreenithalbhat** [ghiscoding/Angular-Slickgrid#171]
**I'm submitting a bug report**

* **Angular Version:**
major.minor.patch

* **Library Version:**
2.5.2

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript ~3.2.2

**Current behavior:** on editing the fields the validation is trigered

**Expected/desired behavior:**
on pasting data in the cells from clipboard validation should be done before pasting and error to be shown

* **What is the expected behavior?**
Copying some data from excel and pasting into angular slick grid need to call custom validation before pasting 

* **What is the motivation / use case for changing the behavior?**
copying data from excel and pasting into grid

**Comment by ghiscoding** [comment]
Could you provide a bit more details, how do you paste? With the right click mouse or with Ctrl+V? Which Editor is that? What is the code you used?

**Comment by ghiscoding** [comment]
Actually I think I see what you mean but it's quite hard to deal with that, what I can do easily is to not paste value that are invalid. What I can't seem to find is how to trigger the `OnValidationError`, just to call the `validate()` inside the Editor doesn't trigger the event.

**Comment by ghiscoding** [comment]
I made a PR #173 and pushed a new version `2.5.5` on [NPM](https://www.npmjs.com/package/angular-slickgrid) that includes the changes which I talked in previous post. The change included in `2.5.5` is that it won't paste an invalid value, it will blank it out when invalid. That is the best I can do for now, I can't find how to trigger the `OnValidationError`. The [demo](https://ghiscoding.github.io/Angular-Slickgrid/#/basic) was also updated

**Comment by sreenithalbhat** [comment]
hey @ghiscoding .Thanks a lot for the update. on Ctlr+ V i wanted to show some validation error message on pasting the invalid data.For time being this update you have done is of great help.
Also i want to keep a column read only in editor and when i paste using Ctrl + V its getting pasted in that column too.Can you please help how to prevent from pasting in that particular column?

**Comment by ghiscoding** [comment]
> But after this update once the cell goes blank for invalid data,am not able to update any other cells with valid data now.Can you please check on this bug.?

I'm not really sure what you mean, because when I did the change, I copy some data into Excel, change some input that I know will be wrong and then paste it back to the grid and I see them blanking. I then go back to Excel, fix the value and paste back into the grid and now the cell has the data because it's valid. So it works on my side, maybe you could add an animated gif of your problem? I use [ShareX](https://getsharex.com/) on Windows for animated gif.

You can see the PR #171 for what was changed, it only blanks the cell value when the input data is invalid. 

> Also i want to keep a column read only in editor and when i paste using Ctrl + V its getting pasted in that column too.Can you please help how to prevent from pasting in that particular column?

Unfortunately I don't think that I have control over that, this feature comes from the SlickGrid core lib as you can see in this [example](http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html) and in it, there are cells that are not editable but it still paste values. Maybe you can ask over to [6pac/SlickGrid](https://github.com/6pac/SlickGrid)

**Comment by sreenithalbhat** [comment]
> I'm not really sure what you mean, because when I did the change, I copy some data into Excel, change some input that I know will be wrong and then paste it back to the grid and I see them blanking. I then go back to Excel, fix the value and paste back into the grid and now the cell has the data because it's valid. So it works on my side, maybe you could add an animated gif of your problem? I use ShareX on Windows for animated gif.

Hey i could fix this issue. thank you

>  there are cells that are not editable but it still paste values. Maybe you can ask over to 6pac/SlickGrid

Okay .I will try that.Thank you for your help.
