### ISSUE TITLE
Autocomplete accept value that is not on the list

### ISSUE THREAD

**Issue by loonix** [ghiscoding/Angular-Slickgrid#174]
**I'm submitting a feature request**

* **Angular Version:**7
major.minor.patch

* **Library Version:**
major.minor.patch

* **Browser:** all

* **Language:**
TypeScript 3.4.5

**Current behavior:**
When added a value on the autocomplete that is not on the list then pressed enter the value goes back to the previous selected value.

**Expected/desired behavior:**
When added a value that is not on the list the autocomplete should give the user a list but if not found the user should be able to add a new one

* **What is the motivation / use case for changing the behavior?**
In case the user wants to add a value that is not included on the list.

PS: I am not sure if this feature already exists

**Comment by ghiscoding** [comment]
The Autocomplete feature was built using the [jQuery UI - Autocomplete](https://jqueryui.com/autocomplete/) because jQuery UI is required by SlickGrid anyway. The question to your question, can jQuery UI do what you want to do? You can look at their documentation, from the link I provided, and if the answer is yes then we can modify the Autocomplete (are you using the Filter or the Editor or both?). 

I personally didn't use it yet even though I built it lol and I'm still unsure on how to replace the `$.ajax` with something that is more Angular style, are you using that as well or a collection of your own?

**Comment by loonix** [comment]
At the moment I am only using the Editor (Collection) as I am building a bulk importer that you can copy/paste values and have pre-filled option to ease the manual 1 by 1.

The replacement for $.ajax should be an httpClient.get?

```
this.httpClient.get(PATH_HERE, {
  responseType: 'json' // or blob
     }).subscribe(res => {
       console.log(res);
 });
```

**Comment by ghiscoding** [comment]
I think I had problem in retrieving `JSONP` (not `JSON`) and I couldn't find how to tell Angular HttpClient about that since the API I found is using `JSONP` and also we can change in which property we send the data by using `$.ajax` and `data: { q: request.term`, anyway like I said I'm not personally using that feature yet, if you see ways to improve then I'm certainly open to PR (Pull Request). Thanks
