### ISSUE TITLE
Any examples of tree tables?

### ISSUE THREAD

**Issue by simplew11** [ghiscoding/Angular-Slickgrid#178]
**I'm submitting a feature request**
**tree tables:TreeTable is used to display hierarchical data in tabular format.**
for example：
![image](https://user-images.githubusercontent.com/25675703/57281428-8ef4c500-70dd-11e9-8ddb-dc4d84a342e6.png)

**Comment by ghiscoding** [comment]
I only made the Grouping example, but if you look at the core lib [Example](http://6pac.github.io/SlickGrid/examples/example5-collapsing.html) and the [code](https://github.com/6pac/SlickGrid/blob/master/examples/example5-collapsing.html), it seems to be easy enough, they use a custom `TaskNameFormatter` and that is about it. 

There is no point for to recreate every single examples of the core lib, I only replicated the most popular ones.

**Comment by ghiscoding** [comment]
I took a stab at it a week ago but that is much bigger than I anticipated. If doable, the Grouping feature is the only viable feature right now that is similar. 

What I got working, but is probably not a good use case, is to expect the dataset to have a `parent` property (root is null), where all the child have this `parent` filled with the `id` of the `parent`. The problem is that the dataset must be sorted and all parent must be a row as well (again sorted), The Sort itself (in the grid) also doesn't work and most probably the Export to CSV would be all broken. 

I don't think this is a good solution, but if you want to take a look at it, I can upload it.

**Comment by Sakkanan** [comment]
Can you please share  your sample?

**Comment by mayankgirdhar** [comment]
Hey please update npm with latest code(slickgrid version in package.json)

**Comment by ghiscoding** [comment]
@mayankgirdhar 
Don't pollute other issues just because you can't read what the `bot` tells you.. which is to fill in the form when creating an issue. Besides there won't be any releases until next year, I'm on holiday.

**Comment by ghiscoding** [comment]
I would like to point out that this is a Work in Progress and I cannot release until I find how to Filter and Sort in a tree structure (possibly in a recursive fashion). I have an open Stack Overflow question, [How to filter multiple properties of a parent child array which could be several tree level deep](https://stackoverflow.com/questions/61034229/how-to-filter-multiple-properties-of-a-parent-child-array-which-could-be-several) and if I can get an answer to it, I could eventually push this feature. 

So please **help** if you can and answer the SO question if you know how. Thanks.

**Comment by ghiscoding** [comment]
This feature will be available shortly, possibly today, but it won't have the 2 things that I've mentioned in earlier [post](https://github.com/ghiscoding/Angular-Slickgrid/issues/178#issuecomment-609922579) (multi-column sort, aggregators), it might in the future but not at this point. I really wish people would contribute but it seems that no one is interested to do so 😢

**Comment by mvgadagi** [comment]
Thanks @ghiscoding for your efforts !!, and providing us this feature very quick :)
