### ISSUE TITLE
Grid within a row detail showings causing some errors. Updating the data in the grid causes the detail rows to hide

### ISSUE THREAD

**Issue by eyandow** [ghiscoding/Angular-Slickgrid#181]
**I'm submitting a bug report**
* **Angular Version:**
7.2.14

* **Library Version:**
2.5.5

* **Browser:**
Chrome 73.0.3683.103

* **Language:**
TypeScript 3.1.1

**Current behavior:**
Putting another slick grid within a slickgrid rowdetail causes the following errors to show up when clicking the '+' button:

> No component factory found for undefined. Did you add it to @NgModule.entryComponents?
and
> SlickGrid requires a valid container, #grid78602 does not exist in the DOM.

#grid78602 is the id generated for the slick grid container.

Also, the row details that are open all close on themselves after a certain amount of time. I am guessing it is due to the errors mentioned above, because if I open multiple at the same time, this happens:
![image](https://user-images.githubusercontent.com/50152763/57380664-68836800-7177-11e9-95a6-3521f68c5f6e.png)

**Expected/desired behavior:**
Be able to have another slick grid within a slick grid row detail and not have the row details close.

**Comment by ghiscoding** [comment]
Wow you are going quite deep in the functionality of the Row Detail. I mentioned in other post that the only code I have done so far with Row Detail is really just the Row Detail Example, I did not use it on anything else and your issue is way too much for my knowledge on the subject. Anyhow, that looks like a racing condition or that you are not using unique `gridId`!? 

I'm afraid that I can't help much more on the subject

**Comment by ghiscoding** [comment]
@eyandow 
I added a new Row Detail option `singleRowExpand` which limit the number of opened panel to only 1 at a time. This might help with your use case, see PR #204

Release to follow shortly

**Comment by ghiscoding** [comment]
@eyandow 
Did you ever managed to fix that and go further? 
I'd like to know if this is still an issue and if this should stay open or not. 
If there are improvements that can be done in the library, feel free to create any PRs in consequence.

**Comment by ghiscoding** [comment]
I will close this issue as something that I won't fix. The Row Detail plugin, as per the name suggest, was created for the sole reason of bringing more details about a row (for example, a list of buyers that when we click on a row it shows their entire address and info). For our project we have to display info and list of items and we decided that showing a sidebar on the right after clicking a row is the best and we can show another grid in that sidebar. Showing a sidebar is easy with Bootstrap grids, we just resize our grid container to 12-4 and 4 on the right for the sidebar, once we close, we resize the grid to fit the container. 

Things to remember if you guys still want to try to show a grid in a grid
1. each grid must have a unique `gridId`
2. SlickGrid doesn't work well when the container of the grid is hidden, SlickGrid needs the container to be shown so that it can calculate the viewport size
  - for that you can possibly wrap the grid in an `*ngIf` and use a `setTimeout` to only display the grid once the row detail is rendered

Lastly, the Row Detail is a plugin of the SlickGrid core library and Angular-Slickgrid is just a wrapper of both SlickGrid and all the external plugins like this one.
