### ISSUE TITLE
How to exclude a column header from the Grid Menu

### ISSUE THREAD

**Issue by CragJWang** [ghiscoding/Angular-Slickgrid#189]
Hello,

I'm using some events to update the columns during running mode, I want to sync up the columns checkbox count in Grid menu, is there any way to do this?
excludeFromHeaderMenu doesn't work for me even I set it before grid load.

**Comment by ghiscoding** [comment]
Hello, I think you have a misconception of what the Header Menu are and they are working fine in the demos. The Header Menu, which is not related to the Grid Menu, is the menu that shows up on top right right corner of a column header title. 

As for the Grid Menu, they always display **all** column header title, including "Select All" checkbox. That comes from the core library (SlickGrid itself), and there is no way to exclude any. That is the expected behavior and not related to current lib. If you want to do something before the grid menu shows up or close or changes, you might be able to use some of the events fired, see all the [Grid Menu Events](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/gridMenu.interface.ts#L101) and the [Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-Menu) on how to use them.

Lastly, please use the issue template for future issues. It helps in understanding the full issue in context, with a couple of questions. 

You can see below, the header menu doesn't show on the "Select All" checkbox, and that is the correct behavior. 
![2019-05-16_09-16-04](https://user-images.githubusercontent.com/643976/57856655-7e1e1080-77bb-11e9-821d-8a832d2ef311.gif)

**Comment by ghiscoding** [comment]
Reference, 
Created a new PR for a new option to exclude a column header from Grid Menu (see PR [#376](https://github.com/6pac/SlickGrid/pull/376) and PR [#377](https://github.com/6pac/SlickGrid/pull/377) for the Column Picker as well)

**Comment by ghiscoding** [comment]
Now released under version [2.7.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.7.0)

**Comment by audrys** [comment]
Hi,
Installed Angular-Slickgrid version 2.7.0
excludeFromColumnPicker: true

columnDefinitions = 
...
{
        id: 'action',
        name:'Actions',
        field: 'id',
        excludeFromColumnPicker: true,
        formatter: myActionButton,
        minWidth: 70,
        maxWidth: 70,
        onCellClick: (e: Event, args: any) => {
          this.openEditSelector(args.dataContext);
        }

Action column still available and active in column picker. Can you help?
R
Audrius

**Comment by ghiscoding** [comment]
Latest version is `2.17.11` so `2.7.x` would be fairly old... nonetheless the flag you're looking for is `excludeFromGridMenu`, you should have it through intellisense or take a look at the [Column interface](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/column.interface.ts#L55). There's 2 flags, 1 for the column picker and 1 for the grid menu.
