### ISSUE TITLE
Android soft keyboard breaks input when enableAutoResize:true

### ISSUE THREAD

**Issue by rubenanton90** [ghiscoding/Angular-Slickgrid#215]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 7.2.13
| Angular-Slickgrid | 2.7.X
| TypeScript        | 3.1.6
| Operating System  | Android 8.0
| NPM/Node/Yarn     | --
| Browser| Chrome for Android, also happens on other browsers

Please close this in case you do not plan to support mobile/tablet browsers. I'm just opening it since the grid appears to work well on Android apart from this issue.

### Context

I'm attempting to use the grid on touch devices. While I understand this component is not meant for mobile (A grid is not very useful on small screen sizes), we'd like to use it in other devices, such as tablets or surfaces.

### Expected Behavior

Inputs should be editable on devices with soft keyboard (ie Android devices).

### Current Behavior

On Chrome for Android, when the enableAutoResize option is set to true, trying to edit a cell results in the soft keyboard showing up. This results in the resize event being triggered, which makes the input lose focus.
### Possible Solution

I tried fiddling with the resizerService.onGridAfterResize subscription and onBeforeEditCell event to give the focus back to the control after the resize happens. While this approach seems to work for the textArea popover, focus is still lost on regular text inputs.

### Code Sample

You can see this happening in the demos, for example at:
https://ghiscoding.github.io/Angular-Slickgrid/#/editor

**Comment by ghiscoding** [comment]
I'm not too sure what to do with that, if I ever look at a grid on a mobile phone, it's never editable because it's just usually too small on a phone. I'm assuming that it does that because the keyboard appearing is triggering a window resize, which is what I use to auto-resize the grid. By searching on that subject, I found this [SO](https://stackoverflow.com/questions/41464434/click-on-input-field-triggers-window-resize-on-android) which confirms exactly what I just said, they also suggest a fix if you're using Cordova (which is not in the lib), to cancel resizing the view with this [answer](https://stackoverflow.com/a/11740286/1212166).

**Comment by ghiscoding** [comment]
I added a PR #216  that might address, hopefully, your issue with some user options. 
1. I changed the `onGridBeforeResize` Observable to return the window resize event (instead of just `true` which is useless). I was hoping that we could do a `e.stopPropagation()` on it, but that would only block the next resize... so probably not good in your use case. However still better to return the Event, so I'll keep that
2. I created a new method called `pauseResizer` which has the name suggest allows you to pause the resizer (when the auto-resize is enabled that is). Hopefully you could work with that...?

I'm planning on releasing a new version tomorrow. I did a refactoring of some Grid Service methods and I was planning a release tomorrow for that. 

I would be happy to get some feedback before I merge. 
Thanks

**Comment by rubenanton90** [comment]
Hi,
PR looks great, I think being able to pause the resizer temporarily would solve my issue. I'll post some code here for future reference if I get it to work on mobile.
Many thanks!

**Comment by ghiscoding** [comment]
@rubenanton90 
I did the release under the new version `2.8.0`, see [here](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.8.0). There's also a [demo](https://ghiscoding.github.io/angular-slickgrid-bs4-demo/#/formatter) of the pause in action, and its [component](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-formatter.component.ts#L120)

Please give that a try and hopefully that would resolve your issue.
Cheers ⭐️

**Comment by rubenanton90** [comment]
Thank you so much, it works fine now!
For future reference, here's what my code looks like

component.html
```
  <div id="feed-container" class="row-content">
            <angular-slickgrid gridId="grid1"
                               [columnDefinitions]="columnDefinitions"
                               [gridOptions]="gridOptions"
                               [dataset]="dataset"
                               (sgOnBeforeEditCell)="onBeforeEditCell($event)"
                               (sgOnBeforeCellEditorDestroy)="onAfterEditCell($event)"
                               (onAngularGridCreated)="angularGridReady($event)">
            </angular-slickgrid>
        </div>
```
component.ts
```

 angularGridReady(angularGrid: AngularGridInstance) {
    this.angularGrid = angularGrid;
  }

  onAfterEditCell($event) {
    this.angularGrid.resizerService.pauseResizer(false);
//after leaving cell editing mode, force a resize to make sure the grid fits the current dimensions
    this.angularGrid.resizerService.resizeGrid();
  }

  onBeforeEditCell($event) {
    this.angularGrid.resizerService.pauseResizer(true);
  }
```

Thanks again!

**Comment by ghiscoding** [comment]
Awesome, I added your code sample to the [Wiki - Editors](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Editors#editors-on-mobile-phone)

You can also up vote ⭐️ if you haven't already 😃 
Cheers and thanks for the feedback
