### ISSUE TITLE
onCellChanged using select multiple row

### ISSUE THREAD

**Issue by sanathpathiraja** [ghiscoding/Angular-Slickgrid#258]
Hi,
I want to select row using when cell data change,

below is working,
  onCellClicked(e, args) {
    if (args.cell !== 0) {
        this.gridObj.setSelectedRows([args.row]);
      }
  }

but i want to do it using onCellChanged event,

please help me.

Thanks.

**Comment by ghiscoding** [comment]
This is a question that could be answered on Stack Overflow, please keep only issues here and ask questions on Stack. Also, please use the issue template structure, it's just a few questions that helps me.

For the `onCellChanged`, you can use `(sgOnCellChange)="onCellChanged($event.detail.eventData, $event.detail.args)"`.

**Comment by sanathpathiraja** [comment]
thanks for comment,
I already use that.
but it not working for row selection.
`(sgOnClick)="onCellClicked($event.detail.eventData, $event.detail.args)"`
cell click event works only one row select and unselect.

I want to do that multiple row selection and unselect using on cell editing.

**Comment by ghiscoding** [comment]
Read the [Wiki - Row Selections](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Row-Selection) and if that is not enough, then I feel that your issue is more of a general question and that should be asked on Stack Overflow. I would prefer to keep only real library issues and keep questions outside

**Comment by sanathpathiraja** [comment]
Thanks for your reply.
