### ISSUE TITLE
#grid1 does not exist in the DOM.

### ISSUE THREAD

**Issue by anakin59490** [ghiscoding/Angular-Slickgrid#26]
Hi,
i follow tuto (https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step)
but i still get this error : ERROR Error: SlickGrid requires a valid container, #grid1 does not exist in the DOM

Thank's

**Comment by ghiscoding** [comment]
Unless you provide more info on what you coded, I can't help you much. Have you provided a `gridId`? Like `<angular-slickgrid gridId="grid1" ...>`

**Comment by ghiscoding** [comment]
Again unless you provide more information, I cannot help you. Please provide code sample of what you tried, else I will end up closing the issue.

**Comment by ghiscoding** [comment]
Closing since no feedback provided

**Comment by coolrb** [comment]
I can reproduce this issue when I am using angular-slickgrid in a tab. Here is the structure
MainComponent - > Has multiple tabs -> One of the tab uses ChildComponent -> Now ChildComponent contains <angular-slickgrid>
The problem is ChildComponent is lazy loaded i.e. DOM does not contain element with id grid1. I infact tried to load component dynamically by

```

> const factory = this.componentFactoryResolver.resolveComponentFactory(SlickGridComponent);
>   const ref = this.viewContainerRef.createComponent(factory);
>   ref.changeDetectorRef.detectChanges();

```
SlickGridComponent - its html template contains angular-slickgrid. But it does not work

**Comment by coolrb** [comment]
Thanks a lot. It helped to fix. It needs a mix of ngIf and initialization of `gridOptions` and `columnDefinitions` in ngInit. Here what I did
`(selectedTabChange)="tabSelected($event)"` added in tab-group. Then checked if the tab is currently selected to show the grid
