### ISSUE TITLE
odata backend service and grouping

### ISSUE THREAD

**Issue by ralcini** [ghiscoding/Angular-Slickgrid#272]
### My Environment
frontend: angular-slackgrid 2.10.1 (my test project is derived from angular-slackgrid-demo)
backend: python

### Context
Starting from angular-slackgrid-demo, I've configured a grid to use a remote backend service implemented in Python. I'm using the latest version of angular-slickgrid 2.10.1. All works fine for me, until I enable the grouping feature..
 
### Expected Behavior
I can expect that the grouping work remotely, for example showing a page with 20 items per page it will show the first 20 groups of level1; when i expand the group to fetch and list all the content (ignoring pagination). It's not so simple to define a effective solution for all the use case, but in any case I expect to be able to disable pagination if grouping and a remote service is configured.

### Current Behavior
If the grouping is active and the pagination too, the grouping feature seems to work clientside: it groups only on the displayed rows of the current page. It works as designed or I've miss some additional configuration? 

I've tried to disable pagination configuring in gridOption enablePagination: false, but in the odata query is present always the parameter $top=25. It seems a bug..

**Comment by ghiscoding** [comment]
So there seems to be a few things in play here... First off, when using grouping, it does the grouping when current dataset since it uses SlickGrid DataView feature, and typically if I need grouping, then I pull all the data I can (by increasing my number of items per page) and then do the grouping. That is the only way that grouping will work, don't expect the grouping to produce a different query with grouping in mind, that's never gonna happen it's just way too complicate. The query builder just produces simple queries and I really don't have time to go in the complicate queries, so that will never change (already that was hard enough to add the new Range Filter in the query builder). 

If your dataset is small enough, I usually go with just a regular API call to retrieve all data and build a regular JSON grid without pagination. Since I always use pagination (when I don't it's because I use a regular JSON grid), I'm not surprised that there's a bug when you try to disable pagination, I always had in mind that it was always shown. I'd be happy to have a PR (Pull Request) with the fix, the issue is probably in `gridodata.service.ts` file.

**Comment by ralcini** [comment]
A quick workaround to disable pagination and have a odata service working properly for me is in the global grid option to set: pageSize: Number.MAX_SAFE_INTEGER and enablePagination: false

>  this.gridOptions = {
         ...
      enablePagination: false,
      ...
      pagination: {
        pageSizes: [10, 15, 20, 25, 30, 40, 50, 75, 100],
        pageSize: Number.MAX_SAFE_INTEGER,
        totalItems: 0
      },
      backendServiceApi: {
        service: new GridOdataService(),
        options: { version: this.odataVersion }, 
        preProcess: () => ...
        process: (query) => ...
        postProcess: (response) => ...
        } }
    };

**Comment by ralcini** [comment]
I will try to study a fix in the next weeks..

**Comment by ralcini** [comment]
thank you for the fix @ghiscoding ! For grouping, I agree with you
p.s. DateRange Filter is veru useful!!

**Comment by ghiscoding** [comment]
Side note that is slightly related to this topic, the latest version [2.16.x](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.16.0) added 2 new flags `useLocalFiltering` and `useLocalSorting` that can, as you can guess by the names, the ability to use local filtering and/or sorting strategies. In other words, you can still use the Backend Service (OData/GraphQL) to initially load the dataset but then have the option to use the in memory DataView to filter and sort afterward.  Also again related to this topic, if you disable the Pagination (`enablePagination: false`), it output a different backend query that will exclude any pagination related stuff when disabled. Again go check the new [version](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.16.0)
