### ISSUE TITLE
De-selection or changing the selection in code - not persisting

### ISSUE THREAD

**Issue by tannenbaums** [ghiscoding/Angular-Slickgrid#278]
I'm submitting a Bug report

### Your Environment
| Angular   7.2.15
| Angular-Slickgrid 2.10.5|
| TypeScript    3.2.4    |
| Operating System: windows 8  |
| NPM/Node/Yarn  NPM 6.0.0  |

### Context
I have the slick grid on one side of the page and a details page on the other side as the user
switches selection the correct details view renders. I would like to give the user
the ability to de-select by clicking on a selected row a 2nd time.
I have tried all the suggestions
such as angularGrid.slickGrid.setSelectedRows([])
nothing works.
Even if I try to select another row through code: 
trying any of theses:
        this.angularGrid.gridService.setSelectedRows([1]);
        this.angularGrid.gridService.highlightRow(1);
        this.angularGrid.slickGrid.setActiveCell(1,1, false, false, true);
doesn't work. When I debug through it, i can see that for while both rows are highlighted (the original one and the one i'm setting in code)
but than at some point the slick grid code gets rid of the new selection. None of my other methods are being hit in the interim so it's not my code that's causing it...
```html
 <angular-slickgrid gridId="caseListing"
                             [columnDefinitions]="columnDefinitions"
                             [gridOptions]="gridOptions"
                             gridHeight="85vh"
                             [dataset]="dataSource"
                             (sgOnClick)="onCellClicked($event.detail.eventData, $event.detail.args)"
                             (onAngularGridCreated)="angularGridReady($event)">
```

```ts
 defineColumns() {
    let that = this;
    this.columnDefinitions = [
      {
        id: 'field1', name: 'field1', field: 'field1', sortable: true, minWidth: 0,
        type: FieldType.string,
        filterable: true, filter: { model: Filters.compoundInput },
        formatter: function (row, cell, value) {
          if (that.dataSource.length < 1) return '';
          return "<div class='highPriority' " + (that.dataSource[row].highPriority ? '' : 'hidden') + "><div style=\"margin-left:30%; margin-top:-85%;\">!</div></div><i class=\"fa fa-circle oval-sm\" aria-hidden=\"true\" style=\"font-size: 10px; color: " + that.dataSource[row].status.color + " \"></i> &nbsp;&nbsp;" + value;
        },

      },
      {
        id: 'field2', name: 'Field2', field: 'field2', sortable: true, minWidth: 0,
        type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput }
      },
      {
        id: 'field3', name: 'Field3', field: 'field3', sortable: true, minWidth: 0,
        type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput }
      }
    ];
  }

 defineOptions() {
    this.gridOptions = {
      autoResize: {
        containerId: 'demo-container'
      },
      fullWidthRows: true,
      rowHeight: 60,
      enableRowSelection: true,
      rowSelectionOptions: {
        // True (Single Selection), False (Multiple Selections)
        selectActiveRow: true
      },
      enableCellNavigation: true,
      enableColumnPicker: true,
      enableExcelCopyBuffer: true,
      enableFiltering: true,
      enableAutoResize: true,
      forceFitColumns: true,
      i18n: this.translate,
    };
  }

  //attempting to de-select a row but doesn't look like the grid allows it
  onCellClicked(arg1, arg2){
      let clickedRow = arg2.row;
      let selectedRows = this.angularGrid.gridService.getSelectedRows();
      let selectedRow = 0;
      if(selectedRows.length > 0) selectedRow = selectedRows[0];
      if(clickedRow == selectedRow){
        //the code reaches here but none of these stay selected as described above
        //this.angularGrid.gridService.setSelectedRows([]);
        //this.angularGrid.gridService.setSelectedRows([1]);
        //this.angularGrid.gridService.highlightRow(1);
        this.angularGrid.slickGrid.setActiveCell(1,1, false, false, true);
       // this.angularGrid.gridService.;
      }
      else{
        this.angularGrid.gridService.setSelectedRows([clickedRow]);
        this.setSelectedCaseId();
      }
  }

setSelectedCaseId(){
  //this will trigger a change event on the details component
    this.selectedCaseId = this.getCurrentlySelectedCaseId();
  }
  getCurrentlySelectedCaseId(){
    let obj= this.angularGrid.gridService.getSelectedRowsDataItem();
    if(obj.length > 0 && obj[0]) return obj[0].id;
    return 0;
  }
```

**Comment by ghiscoding** [comment]
We also have a side detail view and do something similar, but we have a "Close" button in our detail view and we don't care about unselecting the rows. However, we use the Grid object directly instead of the one from the `angularGrid` instance, they should be identical though. 

```ts
handleOnCellClick(event, args) {
  // args contain the grid object so you can use it directly
  grid.setSelectedRows([]);
}
```

but I think your problem is because the event is bubbling up, so I guess you have to stop the event the from bubbling up. You can try

```ts
handleOnCellClick(event, args) {
  // args contain the grid object so you can use it directly
  event.stopPropagation();
  // or 
  // event.stopImmediatePropagation();
  grid.setSelectedRows([]);
}
```
I'm not sure if you need to put it before or after the `setSelectedRows`, I think it would be before. 

Anyway, it's not an Angular-Slickgrid issue, `setSelectedRows([])` is not called anywhere else in the code apart from the `GridService`, so I'm quite sure it's the bubbling event that causes your problem.

**Comment by tannenbaums** [comment]
I tried it, no go. The first option had no effect. The 2nd one stopped the selection from happening in the first place. Is there anything else you would suggest?

**Comment by ghiscoding** [comment]
I didn't think option 1 would change anything since it's the same instance but still good to try. For the option 2, I don't know which part you're trying to do exactly (the clear or the set)? I tried with `setSelectedRows([])` to clear rows and also with `setSelectedRows([0])` to choose first row in `handleOnCellClick(event, args)` in my work project and they're both working fine. 

However in my project, I didn't use `rowSelectionOptions` at all, you could give that a try to see if it's the cause of the problem.

**Comment by tannenbaums** [comment]
I tried both. In the set it stops selection altogether and in the clear, it doesn't have any effect.
I removed the rowselectionoptions and that made no difference either. 
Let me ask you this: would it be possible for you to add it to the demo, so that I can see a working example and work off of that?

**Comment by ghiscoding** [comment]
Sorry but no not at the moment, I just came back from vacations and I have plenty of other things to do.

**Comment by tannenbaums** [comment]
ok not a problem. Maybe you'll have some time at a later date...thank you so much for all your informative responses. very much appreciated!!

**Comment by ghiscoding** [comment]
I tried to copy over your code in the `Example 10` and from what I can see, it seems to work as expected. Note that I took your code and your code doesn't handle selecting more than 1 row which is why the bottom grid only shows 1 row selection. I created and pushed a branch named `issue278` (I will probably delete the branch afterward and not push the code), you can see the code [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/issue278/src/app/examples/grid-rowselection.component.ts#L213) and below an animated gif of this working.


![2019-09-16_19-18-10](https://user-images.githubusercontent.com/643976/64999857-564ccf80-d8b7-11e9-91ae-0cef513d8afc.gif)

**Comment by tannenbaums** [comment]
Yes it works but only in Multiple selections mode. My grid only allows one selection at a time. I tried it in your code and it doesn't work in single selection mode.

**Comment by ghiscoding** [comment]
It does work but only if you click on another cell (not the checkbox column), if that is your issue then it's related to the core lib (SlickGrid) not Angular-Slickgrid. However I don't think it's possible to fix it easily even in the core lib, it might be because it requires `enableCellNavigation` to be `true` and/or how the plugin is built, it might assume that if you are in a single row selection then you'll always have a selection. 

![2019-09-17_11-46-17](https://user-images.githubusercontent.com/643976/65057632-e420cd00-d940-11e9-8b77-0388eeded364.gif)

**Comment by tannenbaums** [comment]
No sorry, I was saying the wrong thing. Now I have it more precise:
I was trying to see why is it that if I turned multiple off from the bottom grid it wasn't working and the top grid had no problem. I finally found the culprit:
the reason the top grid works is because in the column def it has an editor, if I add it to the bottom grid is starts working again.

**Comment by ghiscoding** [comment]
Hmm that is strange, I don't understand how Editor could have an effect but that has to be an issue in the core lib not Angular-Slickgrid. In the meantime I think you can just put `editable: true,` in your Grid Options without declaring any `editors` in your column definitions and that should work as a hack.

**Comment by tannenbaums** [comment]
I see. Unfortunately all of that is still not working in my code base, even putting in an editor or making it multi-select doesn't seem to work. But that's my issue :)
Anyway thank you so much for all your help. I guess I will close it for now. If you have any more info I would appreciate...

**Comment by ghiscoding** [comment]
Ok this works though, disable this grid option `enableCellNavigation: false` and now it works. I don't think cell navigation is important anyway without editing. This way is even better because it works on any cell including the column

**Comment by tannenbaums** [comment]
Oh wow, this finally works in my solution!!! you did it again!!! tysm

**Comment by tannenbaums** [comment]
The thing is though, that with cell nav enabled I was able to go up and down with the up/down arrows and it would change selection. Now I cannot do that anymore. Any idea how I can still get that back?

**Comment by ghiscoding** [comment]
well no that is what `enableCellNavigation` is for. It seems that you can't have both unless you want to troubleshoot the core lib, I know there are side effect with this `enableCellNavigation`, it's not the first I see weird behaviors with this flag, for example this flag has to be enabled when editing but why? Again Angular-Slickgrid basis is just to be a wrapper on top of SlickGrid itself, these kind of behaviors all come from the core.

**Comment by tannenbaums** [comment]
Got it, thank you! Actually one more thing: I noticed (in your example as well) that the top row does not select at first. Only after selecting other rows you can go back and select the top row. Any idea about that?

**Comment by ghiscoding** [comment]
I am not running this branch anymore but on the demo site it works the first time only if I click on the checkbox column not on other cell, then after that it works on any other cells like you said. Must be something in the selection plugin. You can maybe open an issue in the core lib, I contribute there too but it might take some time for a fix.

**Comment by tannenbaums** [comment]
Ok, thank you!
