### ISSUE TITLE
What's the difference between this and the 6pac/SlickGrid fork

### ISSUE THREAD

**Issue by ataft** [ghiscoding/Angular-Slickgrid#282]
I'm trying to understand the logic for when, why and how the Angular-Slickgrid and Aurelia-Slickgrid projects diverge from the 6pac/SlickGrid project. It seems that there are 3 completely separate sets of documentation. It also seems that there are certain non-framework features in the Angular/Aurelia projects that I would think belong in the core project, for example the sort/header and grid menus, CSV export, etc. Can I take advantage of these features with plain JS or React? Wouldn't it make more sense to have one repo with one set of documentation, rather than separate repos for Angular, Aurelia, JS, React, Vue, Polymer, Web Components, etc?

**Comment by ghiscoding** [comment]
These libraries are Framework specific and are wrapper on top of SlickGrid core library, they are programmed for Angular (or Aurelia) only and cannot be used outside of these frameworks. I support both of them because I use Angular at work but I prefer Aurelia in my personal project, the code between them is about 90% the same code and about 10% framework specific. I am not re-inventing the wheel in terms of the grid, I wrap it and make it easier to use in certain framework (I think someone made a VueJS wrapper as well but I never tried Vue and so I never searched for it). There's more documentation in my libraries, yes I spent a lot of time writing them but since they are framework specific, they are completely different from SlickGrid vanilla javascript. My libraries are also written in TypeScript while SlickGrid core still remains plain javascript, that's a big difference. 

SlickGrid in itself is super customizable but that also brings a bad side effect, you have to check the hude amount of examples (1 example per feature) and to try to replicate and mix all options/features you want to use together. My libraries were mostly created to overcome the framework issue but also to make it easier to use in Angular/Aurelia, the biggest difference is how to use Filters/Editors in my libraries, I created a bunch of them and that just doesn't belong in SlickGrid core. There are however a couple of plugins that I worked on directly in the core (I needed a Grid Menu and I created the plugin in the core lib, I also worked with another guy on the Row Detail plugin). I'm the 3rd biggest contributor to SlickGrid (right after 6pac) and that should prove that these libraries are just wrappers and still require SlickGrid core. 

So I hope this answers your questions

**Comment by ghiscoding** [comment]
Oh and for the Export CSV, I could have created a plugin in the core but I wanted Types with TypeScript so I created it only in my repos. If you wish to copy the feature, you could probably just recopy my [ExportService](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/export.service.ts) and remove all the TypeScript stuff and it should work. I added a few Column Definitions & Grid Options to deal with Export (which should be in this [Wiki - Export to File](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Export-to-File) but apart from that it should be easy to copy over and create a plugin. So I could have created a plugin in the core, I just never took the time to recopy it over.

**Comment by ataft** [comment]
Great, thanks for clearing this up. It makes a lot more sense now.
