### ISSUE TITLE
Details view - There is no way to render the grid with all the details expanded

### ISSUE THREAD

**Issue by tannenbaums** [ghiscoding/Angular-Slickgrid#283]
## Feature request

| Angular 7.2.15
| Angular-Slickgrid 2.10.5|
| TypeScript 3.2.4 |
| Operating System: windows 8 |
| NPM/Node/Yarn NPM 6.0.0 |

### Context
I use the grid as a form of a report. The report shows user notes under each row, and it needs to feel natural, so it will not have a way to collapse, it's just always there.

### Expected Behavior
All rows should always be loaded up front and expanded and user has no way to collapse

### Current Behavior
The grid has an Api call: CallapseAll but only allows for one expansion at a time.
I tried expanding in a loop, but it just froze.

### Possible Solution
Introduce a way to have the grid load first time will all it's details view

**Comment by ghiscoding** [comment]
Angular-Slickgrid is just a wrapper of [SlickGrid](https://github.com/6pac/SlickGrid) core library, all the documentation on the Row Detail plugin can be found [here](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js) directly in the core library plugin itself. I don't think what you are looking for exists, but again take a look at the documentation [here](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js)

Personally I think you're going into trouble to open them all in 1 shot, you did experiment with a for loop, and that would most probably be the same code in the plugin if that option would exists. 

I'm closing this since this is not an issue with Angular-Slickgrid

**Comment by tannenbaums** [comment]
Well, I thought that if the api would provide it (as other grids do) it would be more optimized. But 
ok np. I was forced to used another grid for this use case, i really like the slick-grid but... oh well.
