### ISSUE TITLE
UpdateCell or something similar

### ISSUE THREAD

**Issue by ybarbaria** [ghiscoding/Angular-Slickgrid#292]
Hi, 
I am using the function updateItem(...) from the gridService, this works well but I'm looking for something less aggressive, because I have only need to update one cell.  Updateitem it's a bit counter-productive because all the row is rewritten instead of just update the values. Maybe I am not using the good function or I'm missing something. Let me know if you have something :) 

In addition, if the user is editing another cell he loses the focus and what he was writing because the DOM has been updated.

**Comment by ghiscoding** [comment]
We had that problem too in our project, you have to disable the highlight if you don't want to lose the focus on the current cell. SlickGrid by default destroys the `<div>` containing the row/cell and that is why you lose the focus, in fact you're not losing the focus it's simply destroy and you can't focus on a destroyed input. As for the update, that is how SlickGrid deals with the DataView object, there's not really a way (that I know of) to update only the cell (this [SO](https://stackoverflow.com/a/12092344/1212166) basically explains that, and Angular-Slickgrid uses the DataView by default)
```ts
this.angularGrid.gridService.updateItemById(item.id, item, { highlightRow: false });
```

Side this type of questions might be better of asking on Stack Overflow, I would rather keep only real issues in here. Also if you do have an issue, then please use the issue template and fill in the questions since it helps me put the issue in context

**Comment by ghiscoding** [comment]
I'll close the issue since I believe that I answered the problem.
