### ISSUE TITLE
GridService.getSelectedRows return a direct reference of the underlying slickgrid internal array

### ISSUE THREAD

**Issue by whtan98** [ghiscoding/Angular-Slickgrid#294]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8        | 
| Angular-Slickgrid | 2.x        | 

### Context
I noticed that GridService.getSelectedRows return direct reference of underlying slickgrid internal array. 

However, I'm not sure whether this is the intended behavior, but it causes some subtle issue when I try to manipulate the return value as shown below:

```
 this.columnDefinitions2 = [
      {
        id: 'title', name: 'Title', field: 'title',
        sortable: true,
        type: FieldType.string,
        filterable: true,
        onCellClick: (e: Event, args: OnEventArgs) => {
         
         //OK - Able to select the clicked row correctly
         // const selectedRows = [...this.angularGrid2.gridService.getSelectedRows()];

         //NOT OK - Failed to select the clicked row correctly
         const selectedRows = this.angularGrid2.gridService.getSelectedRows();

          // Toggle the clicked row
          const deleteIndex = selectedRows.indexOf(args.row);
          if (deleteIndex >= 0) {
            selectedRows.splice(deleteIndex, 1);
          } else {
            selectedRows.push(args.row);
          }
          this.angularGrid2.gridService.setSelectedRows(selectedRows);
        }
      },


```

**Comment by ghiscoding** [comment]
The GridService is just a helper and a wrapper of many of the slickgrid CRUD methods so yes it mostly return all SlickGrid grid functionalities with some extra. It's there to be a 1 place service to find all CRUD methods with TypeScript typing which helps versus the SlickGrid which has no typing because it's vanilla JS. Also a reminder, Angular-Slickgrid is just a wrapper of the core library SlickGrid, so it's normal that you see the lib calling some methods from the core lib (note that you can also call any of the core lib methods by calling `this.angularGrid.slickgrid.method()`. 

So if there's a problem with the `getSelectedRows`, then it might be in the core lib. There might be another thing that you could try, you can add the `sgOnClick` in your grid and see if there's any differences from the `onCellClick` of the column definitions.
```html
<angular-slickgrid gridId="grid2"
   ...
   (sgOnClick)="onCellClicked($event.detail.eventData, $event.detail.args)"
</angular-slickgrid>
```

One last thing to note is that the `onCellClick` in the column definition was something that I added in the lib [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/gridEvent.service.ts#L45), by default there is no such thing in the column definition, in the end it comes from the `onClick` of SlickGrid (which is `sgOnClick`). 

On a final note, I would try the `(sgOnClick)` to see if there's a difference and if it works with that way, else I'm afraid it would be a core lib issue (but I would be surprised about this though because we would have seen this issue popping up in the core lib which I monitor as well)

**Comment by whtan98** [comment]
I got the same observation using the (sgOnClick) approach for the Not-OK scenario:
1) The checkbox selector is not CHECKED, but those rows are hightlighted
2) sgOnSelectedRowsChanged is not triggered anymore

```
onDebugGridClicked(e: Event, args: OnEventArgs) {
          // OK
          // const selectedRows = [...this.angularGrid2.gridService.getSelectedRows()];

          //Not OK
          const selectedRows = this.angularGrid2.gridService.getSelectedRows();
          // Toggle the clicked row
          const deleteIndex = selectedRows.indexOf(args.row);
          if (deleteIndex >= 0) {
            selectedRows.splice(deleteIndex, 1);
          } else {
            selectedRows.push(args.row);
          }
          this.angularGrid2.gridService.setSelectedRows(selectedRows);
  }
```
OK Screenshot:
![selectrow-ok](https://user-images.githubusercontent.com/13287569/65737145-294ab900-e110-11e9-8d65-cea6db9ac0ab.PNG)

Not-Ok Screenshot:
![selectrow-not-ok](https://user-images.githubusercontent.com/13287569/65737178-3ff11000-e110-11e9-9923-165e708ded65.PNG)

**Comment by ghiscoding** [comment]
I don't fully understand your use case and I don't think I can bring much help to this issue without a functional code sample. If you have the same issue with `(sgOnClick)` then the core lib has the same issue, you might have a racing condition (you can try to add a `setTimeout` and see if that resolves it) or a pointer issue, which you did say that `[...]` fixes it so why not keep that?

**Comment by whtan98** [comment]
Will use the spread workaround for time being. Many Thanks

**Comment by ghiscoding** [comment]
The spread operator makes a deep copy, so it seems that you have pointer issues. I'll close the issue for now and if more details comes up to help this issue then I can reopen it.
