### ISSUE TITLE
Showing different excel files in Slick-grid

### ISSUE THREAD

**Issue by ashishcs062** [ghiscoding/Angular-Slickgrid#30]
Hi,

We have a requirement in our project wherein we are reading different excel files and trying to show them in Slick-grid one at a time. 
The problem that I am facing here is, each excel file will have different column names and values. So it will be like slick-grid columns will keep changing as per the excel file.
Can anyone please suggest me how to implement this?

Thanks,
Ashish

**Comment by ghiscoding** [comment]
You seem to have multiple challenges and I don't fully understand them all. A few notes though
- with last week release, Angular-Slickgrid now support Dynamic Column Headers, you can change columns on the fly
- Angular-Slickgrid does not currently support multiple grids in a view. 
   - I tried changing the Services that are all singleton to non-singleton but then it broke all my services and will have to rethink about that, most probably a Major (breaking) version will be required to address these
   - however we need multiple grids in my current project so this will be addressed in the coming month or weeks
- just to be sure, are you talking about reading and displaying or exporting to Excel? Because we usually only mention Excel when it's time to export data

**Comment by ghiscoding** [comment]
Multiple Grids is now available with new [release 1.0.0](https://github.com/ghiscoding/Angular-Slickgrid/releases) (Beta)

This is a Major version and contains a few breaking changes, you can read the [Migration Guide](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Migration-from-0.x-to-1.x)

I'm also still waiting for more details from your side, that is you still need help

**Comment by ghiscoding** [comment]
closing as no feedback was provided and a new Major release `1.x` is shipped
