### ISSUE TITLE
Any example of a dropdown menu in a particular cell

### ISSUE THREAD

**Issue by jeremielodi** [ghiscoding/Angular-Slickgrid#304]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8        | 
| Angular-Slickgrid | x.y        | 
| TypeScript        | x.y        | 
| Operating System  | x.y        | 
| NPM/Node/Yarn     | x.y        |

**Comment by ghiscoding** [comment]
I believe this is a duplicate of issue #248 and if so, there's an example on how to do it yourself in it

**Comment by jeremielodi** [comment]
What I mean is totaly like this :

**Comment by jeremielodi** [comment]
In the picture I use ui-grid of angular 1.x

```js

  {
      field: 'Actions',
      width: 100,
      displayName: '',
      enableFiltering: false,
      cellTemplate: 'modules/school_management/enrollment/templates/action.cell.html',
    }

**Comment by jeremielodi** [comment]
@ghiscoding this is a kind of formatting, it is not a context menu

**Comment by ghiscoding** [comment]
Perhaps you're looking for [this](https://ghiscoding.github.io/Angular-Slickgrid/#/angular-components) or just use a [Custom Formatter](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Formatters#custom-formatter), just read the Wiki or if you are still confused, I suggest you ask that kind of questions on Stack Overflow.

**Comment by jeremielodi** [comment]
OKay, I'm trying to use component and see I will be able to implement that

**Comment by jeremielodi** [comment]
![2019-10-08_06-58-11](https://user-images.githubusercontent.com/25838121/66370915-b48e3f00-e999-11e9-9815-4e95fd1373cd.gif)

**Comment by jeremielodi** [comment]
If in the future we can have a property called 'cellTemplate' that will help to load the html template from a url or text in cell definition, we will make things easy.
And in side the template use can use the component scope for accessing methods ...


Something like this will be awsome
```js
{
      field: 'Actions',
      width: 100,
      displayName: '',
      enableFiltering: false,
      cellTemplate: 'modules/school_management/enrollment/templates/action.cell.html',
    }

**Comment by ghiscoding** [comment]
A `cellTemplate` is a `Formatter` in SlickGrid and that is what you have to use. We used UI-Grid in AngularJS projects before and there's nothing we can't do with Angular-Slickgrid compare to UI-Grid.

**Comment by ghiscoding** [comment]
I give that a quick try at it, it's more complicate than I imagine, mainly for the following reason
- Angular-Slickgrid is a wrapper on top of SlickGrid which is a jQuery library... meaning that the core of the lib is not written in Angular which makes it harder to deal with custom Angular (a problem that UI-Grid didn't have because it was written in Angular)
- You cannot use just a Formatter because a SlickGrid Formatter always expect an html string to return right away (and instantiating an Angular Component is not returning right away)
- the dropdown list doesn't show when using a custom formatter and using `z-index` doesn't help, that is how SlickGrid is built and the only way to get over this problem is to move the dropdown to the document body.

I got a quick sample working by following these steps
1. Use a Custom Formatter just to show the Bootstrap Dropdown button (note that it's an empty shell without any action list, the real one that will be used comes from the Angular Component on step 3)
2. Add the Custom Formatter to your column definition
3. Create an Angular Component with the real Bootstrap Dropdown with the list of Actions which we'll use `(click)` event to trigger the action
4. Add the Angular Component to the Angular App Module in the `declarations` and `entryComponents`
5. add `(sgOnActiveCellChanged)` to your Angular-Slickgrid component
6. add the action in your component (I added a delete action in the component where the grid is but I guess you could also move the code to the action component)
7. add the `onActiveCellChanged` method in your component which will instantiate the Action Angular Component and also append this new DOM element to the body container (because we cannot show a list within a grid cell). 

See the [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/ba6082cb68a7552c7688dda510df42a528455a26) for the complete list of changes. 

I might simplify this process in the future by moving this into a separate service, but even if I do, there are some steps that just cannot be removed (at least step 3-4 will always be required by the user). 

and finally it works!
![2019-10-08_17-41-50](https://user-images.githubusercontent.com/643976/66435484-f13a5480-e9f2-11e9-91c7-c6c6a8dd2d6c.gif)

**Comment by jeremielodi** [comment]
Thanks a lot

**Comment by ghiscoding** [comment]
The [GitHub Demo](https://ghiscoding.github.io/Angular-Slickgrid/#/angular-components) and the [angular-slickgrid-demos](https://github.com/ghiscoding/angular-slickgrid-demos) just got updated as well. You can see the live demo [here](https://ghiscoding.github.io/Angular-Slickgrid/#/angular-components)

**Comment by jeremielodi** [comment]
It's a very good start 👍

**Comment by jeremielodi** [comment]
you can add the ability in this medthode ```onActiveCellChanged(event, args) {``` to hide the dropdown when the user click elsewhere on the window 
```js
     // use a delay to make sure Angular ran at least a full cycle and make sure it finished rendering the Component before using it
    setTimeout(() => {
      const elm = $(componentOutput.domElement);
      elm.appendTo('body');
      elm.css('position', 'absolute');
      elm.css('top', cellPos.top + 3);
      elm.css('left', cellPos.left);
      $('#myDrop').dropdown('show');

      $('#myDrop').on('hidden.bs.dropdown', () => {
        formatterElm.show();
      });
       
     // hide dropdown menu
      $(window).click(() => {
        $('#myDrop').remove();
      });
    });
```

**Comment by jeremielodi** [comment]
I did some manipulations on the dropdown in order to improve it behavior a bit.
You can see how it works now
![2019-10-10_07-32-03](https://user-images.githubusercontent.com/25838121/66544889-467c8000-eb31-11e9-892e-57f0e4b64f56.gif)

**Comment by jeremielodi** [comment]
Here is my code

grid-angular.component.js
```js

onActiveCellChanged(event, args) {
    $('#myDrop').remove(); // make sure to remove previous Action dropdown, you don't want to have 100 after a 100 clicks...
    console.log(args);
    if (args.cell !== 6) {
      return; // don't do anything unless it's the Action column which is at position 6 in this grid
    }

    const cell = args.cell;
    const row = args.row;

    // hide the dropdown we created as a Formatter, we'll redisplay it later
    const formatterElm = $(`#myDrop-r${row}-c${cell}`);
    const cellPos = formatterElm.offset();

    const componentOutput = this.angularUtilService.createAngularComponent(CustomActionFormatterComponent);

    // pass "this" and the row number to the Component instance (CustomActionFormatter) so that we can call "parent.deleteCell(row)" with (click)
    Object.assign(componentOutput.componentRef.instance, { parent: this, row: args.row });

   
    // use a delay to make sure Angular ran at least a full cycle and make sure it finished rendering the Component before using it
    setTimeout(() => {
      const elm = $(componentOutput.domElement);
      elm.appendTo('body');
      elm.css('position', 'absolute');
      elm.css('top', cellPos.top + 30);
      elm.css('left', cellPos.left);
      $('#myDrop').dropdown('show');

      // check if it should drop up or drop down
      var offset = 35;
      const iElement = $('.dropdown-menu');
      const iElementWrapper = iElement.parent();
      const iElementWrapperOffsetTop = iElementWrapper.offset().top;
      const iElementHeight = iElement.height();
      const windowHeight = $(window).height();
      const shouldDropUp = (windowHeight - iElementHeight - offset) < iElementWrapperOffsetTop;
      const menuMarginTop = shouldDropUp ? '-'.concat(`${iElementHeight + 30}`, 'px') :'0px';
      elm.css({ 'margin-top' : menuMarginTop});
      
      // set dropdown margin left according to the document width
      const parentOfset =  iElementWrapper.offset().left;
      const leftMargin =  parentOfset -  $(document).width();;
  
      elm.css({ 'margin-left' :( elm.width() +  leftMargin) +'px' });
      // avoid duplication of actions
      $('#dropdownMenu1').css('display', 'none');

      $('#myDrop').on('hidden.bs.dropdown', () => {
        formatterElm.show();
      });
     
      // hide the dropdown on window clik
      $(window).click(() => {
        $('#myDrop').remove();
      });

    });
  }
```
columns definition
```js
{ id: 'action', name: 'Action', field: 'id', cssClass : 'pointer', minWidth: 40, formatter: customActionFormatter, width: 70 }
```
<u> grid-angular.component.scss</u>
```css
.pointer{
  cursor: pointer !important;
}
```


<u>custom-actionFormatter.component.ts</u>
```js

import { Component } from '@angular/core';

@Component({
  template: `<div id="myDrop" class="dropdown pointer" style="position:relative; z-index:12000;">
  <a href class="dropdown-toggle" id="dropdownMenu1"
   data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Action
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <a class="dropdown-item pointer" >action1</a>
    <a class="dropdown-item pointer">action2</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item pointer" (click)="parent.deleteCell(row)">Delete Row</a>
  </ul></div>`

})
export class CustomActionFormatterComponent {
  parent: any;
  row: number;
}
```

**Comment by jeremielodi** [comment]
I'm trying to do a PR but it seem that something is not good

my branch <a href='https://github.com/jeremielodi/Angular-Slickgrid/tree/dropdown-formatter'>here</a>

 modified:   bootstrap4-demo-with-translate/src/app/examples/custom-actionFormatter.component.ts
  modified:  bootstrap4-demo-with-translate/src/app/examples/ grid-angular.component.scss
   modified:  bootstrap4-demo-with-translate/src/app/examples/ grid-angular.component.ts
 create mode 100644 bootstrap4-demo-with-translate/src/app/examples/dropdown.service.ts
