### ISSUE TITLE
Unable to expand row detail programmatically

### ISSUE THREAD

**Issue by whtan98** [ghiscoding/Angular-Slickgrid#318]
## Question
Based on "Example 21: Row Detail View",  I  expanded the 2nd  row  programmatically using 
 "expandDetailView" method. But the expanded row detail went blank after scrolling up/down a few times. See attach picture.

Also is there a way to expand all the rows on initial load?

Please advise.

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8.x        | 
| Angular-Slickgrid | 2.12        | 

### Context

My intention is to expand all the rows in the current page, in order to perform a bulk update  in one go.

### Code Sample
```
  expandSingleRow() {
    if (this.angularGrid && this.angularGrid.extensionService) {
      const x = this.angularGrid.dataView.getItem(1);
      this.rowDetailInstance.expandDetailView(x);
    }
  } 
```
![missing-detail gif](https://user-images.githubusercontent.com/13287569/67157779-9514f000-f363-11e9-919e-1af9d36930d4.gif)

**Comment by ghiscoding** [comment]
First of all, this is SlickGrid core plugin, Angular-Slickgrid is just wrapper, the plugin has a way of calculating if the row detail panel is out of view or not. The calculation is on this [line](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js#L347). If you want to tweak the calculation then do a PR in the core lib, I spent way too many hours on trying to optimize it and I don't want to spend a minute more (I don't even use this plugin yet). 

SlickGrid uses caching (about 5 extra rows on top/bottom), it never populates the entire grid which makes SlickGrid an extremely fast grid even with 50k rows since it will never show the entire dataset in the DOM, doing so is going to kill your browser in most case. 

So to answer your question of 
> My intention is to expand all the rows in the current page, in order to perform a bulk update in one go.

That won't be possible, since like I said earlier SlickGrid never shows the entire dataset in the DOM (unless it fits in the screen). There is also no method to open all the rows at once because every time a row detail opens, we have to re-render the DOM and opening all rows at once will be extremely slow and also not possible because of the caching mechanism of SlickGrid. 

So I'm affraid you're looking at the wrong plugin to achieve what you want. This plugin was created, as the name suggest, to view more details of the selected row and possibly do some CRUD on it. What you're trying to do is just overkill for this plugin

**Comment by whtan98** [comment]
Thank you for the  insightful explanation. Really appreciate it

**Comment by ghiscoding** [comment]
>  I can make this redrawAllViewComponents method public if that would help, you would simply have to subscribe to the onScroll event and call that redrawAllViewComponents (for example, I use it after user starts filtering).

If that makes any difference [redraw/render](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts#L208) are now all public, I pushed a new patch version this morning which includes this and other small fixes.
