### ISSUE TITLE
Excluded menu item is still displayed in Bootstrap4

### ISSUE THREAD

**Issue by whtan98** [ghiscoding/Angular-Slickgrid#321]
## I'm submitting a Bug report
It seems that  "hidden" class is no longer available in Bootstrap 4. 
This causes those hidden menu items in GridMenu  become visible.

https://ghiscoding.github.io/angular-slickgrid-demos/#/editor

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8        | 
| Angular-Slickgrid | 2.12        | 

### Current Behavior

![image](https://user-images.githubusercontent.com/13287569/67257843-8001a380-f4c0-11e9-84b0-2b9782879297.png)

**Comment by ghiscoding** [comment]
Good catch, I wasn't aware that this class was removed in BS4, we still use BS3 for our project so. 
You can use the following SASS style, I tried it in the BS4 demo and it works. 

```scss
.slick-gridmenu-list {
  li.hidden {
    display: none;
  }
}
```

I recommend you do this change on your local, because I'm not planning on releasing a new version  just for this (I released yesterday).

**Comment by whtan98** [comment]
Many thanks for prompt response !

**Comment by ghiscoding** [comment]
This was pushed under latest version `2.12.3`
