### ISSUE TITLE
2.13.0 no longer runs in Firefox

### ISSUE THREAD

**Issue by whtan98** [ghiscoding/Angular-Slickgrid#336]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8        | 
| Angular-Slickgrid | 2.13.0        | 
| Firefox | 70.0.1 (64-bit)       | 
### Context

All examples using release 2.13.0 does not run in Firefox anymore,  with "SyntaxError: invalid regexp group" printed in the web console
However it runs ok in chrome though.

See https://ghiscoding.github.io/angular-slickgrid-demos/#/basic

**Comment by ghiscoding** [comment]
Yeah I saw that, I thought it came from the bundle target to `ES2015` but actually after digging for an hour I found that it came from this 1 line of code that I added to display Thousand Separator on all Formatters, that is
```ts
return stringValue.replace(/(?<!\.\d+)\B(?=(\d{3})+\b)/g, separator);
```

[Regex Lookbehind](https://github.com/tc39/proposal-regexp-lookbehind) Expression (which I didn't know what that was) are not supported in Firefox (but works in Chrome) because it's not yet standardized (though it's at stage 4). So anyway, I've found a patch that works, but it's not as clean as prior code.

**Comment by ghiscoding** [comment]
I just pushed a patch version `2.13.1` that includes this fix.

**Comment by whtan98** [comment]
I'm not aware of the Lookbehind regex feature, in fact  i'm totally lost in my attempts to debug the JS error in firefox.

Many thanks for prompt patch.

**Comment by ghiscoding** [comment]
Thanks for reporting, this was an important bug to be fixed and I made it urgent since we also have bi-weekly release of our app and we didn't want this bug be released in production.
