### ISSUE TITLE
Filter issue after using latest angular-slickgrid

### ISSUE THREAD

**Issue by SureshNegi** [ghiscoding/Angular-Slickgrid#349]
Posted the query in below link:
https://stackoverflow.com/questions/59091043/angular-slickgrid-filter-not-working-filter-is-working-if-complete-text-is-typed

**Comment by ghiscoding** [comment]
I will reply the same thing I wrote in your other issue, which is more of a question...

I have Cypress E2E tests and they are all passing, so I doubt the library has any issues and I just reached 100% test coverage. I'm quite sure the issue is on your side. The Angular-Slickgrid demos are all fine, unless you can provide full way of replicating your issue, I can't help you.

Also please fill in the issue template the next time

**Comment by ghiscoding** [comment]
After some investigation, I found out that it's a valid bug and it happens in this [Example 12](https://ghiscoding.github.io/Angular-Slickgrid/#/localization) and is not covered under unit tests. 

It would have been much easier if you would have point me to one of the GitHub demos. I'd like to give you some recommendations for future issues
- please fill in the GitHub issue template
- try reproducing the bug, if it is a bug, in the GitHub demos
- for any questions on how to do such a such a thing, please use Stack Overflow

Thanks and I will fix this today

**Comment by ghiscoding** [comment]
Fixed and released under [version 2.14.3](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.14.3)

**Comment by SureshNegi** [comment]
Thanks for quick fix
