### ISSUE TITLE
css problem

### ISSUE THREAD

**Issue by figuerres** [ghiscoding/Angular-Slickgrid#366]
i am trying to use this grid but it seems like the css is broken in some way but i have no idea what is wrong. trying to use bootstrap 4  and angular 8  nav menu is ok but the grid is all stuck in one mess....
the instructions on the setup were rather confusing so i must have got it wrong but how to fix it i do not know....

**Comment by ghiscoding** [comment]
This is more of a [Stack Overflow](https://stackoverflow.com/) question, I won't answer it here and as the `bot` says, next time fill the entire issue template (which is why it was auto-closed by the bot). 

I provided plenty of Wikis and also Angular-Slickgrid-demos which is enough to get anyone started.

**Comment by figuerres** [comment]
and i dont have time.... trying other stuff.... found one that works.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
