### ISSUE TITLE
vulnerabilities in my project

### ISSUE THREAD

**Issue by gyanex** [ghiscoding/Angular-Slickgrid#377]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8.0.0       | 
| Angular-Slickgrid | 2.16.0       | 
| TypeScript        | 3.4.5       | 
| Operating System  | win32 x64        | 
| NPM/Node/Yarn     |   12.13.0      | 

### Context or Topic 
when i run "npm i angular-slickgrid" it produces 35+ vulnerabilities in my application

### Expected Behavior
should be installed without vulnerabilities and successfully build in production mode

### Current Behavior
Creates vulnerabilities and throw error "ERROR x-y.js from Terser undefined"  on prod build

**Comment by ghiscoding** [comment]
Please be a bit more specific than that, you wrote about lodash in the other issue but I can't unfortunately update that one, it comes from this package `excel-builder-webpack` (to provide Export to Excel) and it wasn't updated in a long time. Apart from that I don't believe that my lib has 35 vulnerabilities when the list of dependencies is about 10 packages

**Comment by ghiscoding** [comment]
I created a separate lib [excel-builder-webpacker](https://github.com/ghiscoding/excel-builder.js) with update npm packages including latest lodash, which I now use in the lib with this PR #378 so that should fix the vulnerabilities. I also wanted to push a new version [2.16.1](https://github.com/ghiscoding/Angular-Slickgrid/releases) with some other small fixes, so you're lucky enough to have it fix already. 

Please upvote, if you haven't already, if you like the lib ⭐️

**Comment by gyanex** [comment]
Everything is fine, but after importing AngularSlickGridModule.forRoot() in my root module when i build it in prod mode it stuck TerserPlugin for few seconds and throw a new error.
![Annotation 2020-01-21 233723](https://user-images.githubusercontent.com/45200081/72830598-0fc51280-3ca7-11ea-9532-578fa616341c.png)

**Comment by ghiscoding** [comment]
most probably a problem on your side, every PR I make runs unit tests and also does a build with CircleCI. Also in addition to that, I also update (every single time) the [Angular-Slickgrid-Demos](https://github.com/ghiscoding/angular-slickgrid-demos) for Bootstrap 3 and 4, which are used for the GitHub Demos page, and those run an Angular Production Build... so it has to be on your side. Perhaps delete your `node_modules` folder and redownload it afterward, and you should also delete your `yarn.lock` (or the npm lock file) to remove any issue related to version not in synch.

Again the  [Angular-Slickgrid-Demos](https://github.com/ghiscoding/angular-slickgrid-demos) was created to test the build but also for people to refer to, I suggest you take a look at them. The `forRoot` requires to provide options if I remember correctly it might fail if it's empty

**Comment by gyanex** [comment]
Here is my github respository to generate the error
https://github.com/gyanex/angular-slick-test.git

please help if you can. thanks in advance @ghiscoding @DreamerRahul

**Comment by ghiscoding** [comment]
Sorry but I already provided enough information for you to troubleshoot on your own. I would suggest that you clone the [Angular-Slickgrid-Demos](https://github.com/ghiscoding/angular-slickgrid-demos) as a starter. Like I said, I test every single release that I do with Angular production build, the problem is on your side. 

I also need to remind you that this is Open Source library which I am not paid to develop and provide to the world for free. So I'm sorry but I don't have time to help you more than that.

**Comment by ghiscoding** [comment]
I took a look at your test repo and the problem is that your `angular.json` has none of the `scripts` and `css` import files that are required for this library to work and this is all written in the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step)  and is also included in all of the [Angular-Slickgrid-Demos](https://github.com/ghiscoding/angular-slickgrid-demos).

So congratulation, you just made me lose 1 hour of my time 👎 by replying all of your questions, to end up finding that you, as a user of my Open Source lib, did not follow any of the **recommended** and **necessary** instructions that I kept telling you about. 😱 

I have to admit that the security vulnerabilities were worth fixing, congrats on that... but your question about the build is quite frustrating. I created all of these [Wikis](https://github.com/ghiscoding/Angular-Slickgrid/wiki) over the past 2 years for a reason and now you learned the hard way by not following any of it.
