### ISSUE TITLE
Error "NullInjectorError: No provider for  X" in version 1.0.15

### ISSUE THREAD

**Issue by sabeurch** [ghiscoding/Angular-Slickgrid#38]
First of all, thank you this great job on removing the singleton services usage.
I upgraded the angular slick version into 1.0.15 this morning (latest).
I followed all instructions as described in [Migration-from-0.x-to-1.x](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Migration-from-0.x-to-1.x)

No compilation Error, but I get this error when opening the view:
```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[MyGridTestComponent -> GridService]: 
  StaticInjectorError(Platform: core)[MyGridTestComponent -> GridService]: 
    NullInjectorError: No provider for GridService!
```

I followed the instructions to resolve this issue based on stack trace messages, so I found that I have to provide the service "GridService" inside my component (no singleton service).
Other services are also provided (each time the error message changes, I add the necessary providing).

Finally, to got it working, I was obliged to provide all this list of services internally to my component:

```
 providers :[ AngularSlickgridComponent, GridService, ControlAndPluginService, ExportService, 
               FilterService, SortService, GridStateService, ResizerService, 
               FilterFactory, SlickgridConfig]
```
NB: Services FilterFactory and SlickgridConfig are not exported by default (ie version from npm).
So, I built the library and made them public. I installed the locally modified library.

NB: I tried the provide only "SlickPaginationComponent" as it become a service, but it fails with the same message error.

NB: Maybe one other possibility (that I haven't tested): MyGridTestComponent  will extend **AngularSlickgridComponent** , I think I will not be in a need to rebuild the library, but I'll have provide about 10 services to pass them as arguments to the super class 'AngularSlickgridComponent'

My question:  Am I doing wrong from the beginning ?
Do we really need for this number of services to be injected (provided) ?

**Comment by ghiscoding** [comment]
indeed there isn't any Services exported anymore in version `1.x`, it is intended because all these services are non-singleton (except inside the component itself) and should not be provided as DI. If there's anything to do, it has to be through the `AngularSlickgrid` instance. I did ask you some questions [here](https://github.com/ghiscoding/Angular-Slickgrid/issues/31#issuecomment-391161048) when I was doing the refactoring, you told me it was ok to remove all DI.

**Comment by ghiscoding** [comment]
@sabeurch 
By the way, your Grid Component is still part of my lib and I got it working with some changes, so you should see what changed in that [swt grid component](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/swt-common-grid.component.ts). It's actually a good thing that you made it part of my lib, I made sure the refactoring still had that external pagination working before releasing anything :P

**Comment by sabeurch** [comment]
@ghiscoding 
From inside the Angular slick grid project all is OK, demo is working fine, 
But, it get not working in an external project unless I provide dependencies.
Please confirm if you already worked with it as a library installed from npm ?

**Comment by sabeurch** [comment]
Good to hear about that. So problem is probably in my migration. I'll compare the 2 versions in the demo, see what changes been done, and apply to my project. I'll write sooner.

**Comment by ghiscoding** [comment]
The 2 files you mentioned are new files in version `1.x` and yes I didn't export them because they are used internally. Not sure why you need them exported when you are working with Pagination?

You know that you can easily clone the repo locally and run the VSCode task "Start Library Dev" (or run npm start in console). All the examples are within the lib. Isn't that easier for you to test what works on your side first?

**Comment by sabeurch** [comment]
@ghiscoding , 
I am working with and without pagination. 
I need all those services 
 **providers :[ AngularSlickgridComponent, GridService, ControlAndPluginService, ExportService, 
               FilterService, SortService, GridStateService, ResizerService, 
               FilterFactory, SlickgridConfig]**
to be provided internally in the SwtCommonGrid component (the componet that wraps AngularSlickGrid component).
All of those services are provided locally to the SwtCommonGrid component, which means I am not using them as Singletons.
If I do not povide them, then I'll have this error: 
```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[MyGridTestComponent -> GridService]: 
  StaticInjectorError(Platform: core)[MyGridTestComponent -> X]: 
    NullInjectorError: No provider for X!
```
But, as services FilterFactory and SlickgridConfig are not publically exported, Yes,  I did a clone on version angular-slickgrid@1.0.19 , did the changes to make them exported (as clarified in my previous comment), created the tgz and imported it in my project.
All features are working on my side, as well as for All examples in the SlickGrid project.
Thanks,

**Comment by ghiscoding** [comment]
I exposed the `SlickGridConfig` and `FilterFactory` in latest version `1.1.0`, both are exported through the `angular-slickgrid\index.ts`

Note, in your comment, you mentioned:
> You will just export them from:
"src\app\modules\angular-slickgrid\filters\index.ts" => export * from './filterFactory';

This was incorrect, since it was throwing a warning of circular dependency. Exporting it inside the Angular-Slickgrid `index.ts` (as mentioned on top) is ok though. 

I don't want to expose all the Services, so hopefully that is enough for you to get going.

**Comment by sabeurch** [comment]
Many thanks Ghislain !
I'll download and give it a try, then confirm the closure of this ticket.

**Comment by sabeurch** [comment]
It works perfectly.
You can close this ticket.
Gracias.
