### ISSUE TITLE
DatePicker in edit mode not working

### ISSUE THREAD

**Issue by MasiGit** [ghiscoding/Angular-Slickgrid#414]
**AngularSLickGrid Version**

  "_from": "angular-slickgrid",
  "_id": "angular-slickgrid@2.15.4",
  "_inBundle": false,
  "_integrity": "sha512-HXwuB4gI2DQTi6SEet8goNuCu5DlaJxz7wzL4Ek5BdLBRLfQxSq5j28NpIzbjdBGKrM3Qz51YHkC5nA7lwnn9A==",
  "_location": "/angular-slickgrid",

**FlatPickr version**
{
  "_from": "flatpickr@>=4.5.0",
  "_id": "flatpickr@4.6.3",
  "_inBundle": false,

**Grid Options**

 { id: 'validUntil', name: 'Valid Until', field: 'validUntil', formatter: Formatters.dateIso,
      exportWithFormatter: true,
      type: FieldType.date,
      editor: {
        model: Editors.date
      },
      onCellChange: (e: Event, args: OnEventArgs) => {
        this.onCellChangeEvent(args)
        
      }},
      
    ];

    this.gridOptions = {
      autoResize: {
        containerId: 'request-id',
      },
      enableAutoResize: true,
      enableSorting: false,
      enableHeaderMenu: false,
      enableGridMenu: false,
      enableAutoTooltip: true,
      // contextMenu:{hideExportExcelCommand:true},
      enableContextMenu: false,
      editable: true,
      autoEdit: false,
      enableCellNavigation: true,
      enableColumnPicker: false,
      forceFitColumns: true,
      // autoCommitEdit: true,
      
      
    };

On clicking the cell the calendar does not popup

**Comment by ghiscoding** [comment]
I'm not sure why the bot didn't close your issue but it should have because your issue is really hard to read and you're not providing enough details. 

Have you read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step#2-modify-the-angularjson-and-tsconfigappjson-files) on that section it says to add the Flatpickr styling, did you?

> On clicking the cell the calendar does not popup

According to your Grid Options, it won't open on a single click but will open on a double click. If you want to open on a single click then you need `autoEdit: true` in your grid option, when false it's on a double click.

If you go to the [Example 3 - Editors](https://ghiscoding.github.io/Angular-Slickgrid/#/editor), you can see it totally works and that GitHub Demo is updated every single time I do a release. I suggest you to clone the [Angular-Slickgrid-Demos](https://github.com/ghiscoding/angular-slickgrid-demos) and get started from there. 

I'm closing your issue because there are not enough detail to prove that the lib has issues. Also your issue seems more like a question and I encourage people to ask questions on [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=slickgrid), you will have more help from there.

**Comment by MasiGit** [comment]
Thanks, will move to SO going forward for such kind of questions.
Have a safe and great day!
