### ISSUE TITLE
Row detail and pinning columns not working together

### ISSUE THREAD

**Issue by meta-akshita-agrawal** [ghiscoding/Angular-Slickgrid#442]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.0        | 
| Angular-Slickgrid   | 2.17        | 
| TypeScript              | 3.7        | 

### Describe the Bug

Hi @ghiscoding,
Thanks for making such a great library :)
I am creating this report as I faced an issue when having row detail functionality and pinned columns. Please find the below screenshot attached 

### Steps to Reproduce

Add **frozenColumn : 2** in the gridOptions of the given example 
https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-rowdetail.component.ts

**Comment by meta-akshita-agrawal** [comment]
![Screenshot (92)](https://user-images.githubusercontent.com/41181785/81045507-f782a780-8ed3-11ea-8155-22e50da50bd8.png)

**Comment by ghiscoding** [comment]
That is a core lib (SlickGrid) issue, not related to Angular-Slickgrid and most probably will be hard to fix because the pinned columns are 2 individual `<div>` (1x on the left and 1x on the right) which is why you get this issue and there's a big chance this will never get fixed unless you find a way to fix it in CSS somehow... so I would recommend not to use the 2 things together
