### ISSUE TITLE
Example 19 Draggable Grouping & Aggregators

### ISSUE THREAD

**Issue by pwidanka** [ghiscoding/Angular-Slickgrid#464]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.0        | 
| Angular-Slickgrid   | 2.18.6       | 
| TypeScript              | 3.75        | 

### Describe the Bug

Badly show grid height, i don't see all rows and overflow-x if I uncheck force fit columns
![image](https://user-images.githubusercontent.com/31447178/82483565-dd9eb280-9ad8-11ea-93cc-9c60704ec176.png)

### Steps to Reproduce

Example 19
### Expected Behavior

Show all grid rows
### Current Behavior

I don't see all rows

**Comment by ghiscoding** [comment]
Please provide more info next time, I was about to close the issue because I barely understood what you wrote. This new issue is a problem in the SlickGrid core lib, because of this [change](https://github.com/6pac/SlickGrid/commit/af6151fbb7098bc22adfa37a7ad28a1a7ce7c637) related to this [issue](https://github.com/6pac/SlickGrid/issues/493)

**Comment by ghiscoding** [comment]
This is now fixed in latest version [2.18.x](https://github.com/ghiscoding/Angular-Slickgrid/releases). 

Please upvote ⭐ if you haven't already. 
Cheers
