### ISSUE TITLE
Column filters (multiselect) does not filter on checkbox click..

### ISSUE THREAD

**Issue by wshreya** [ghiscoding/Angular-Slickgrid#484]
Hello Team, 

I am using multiselect column filter in my project. However, the data is filtered only when we click okbuttton. Is there ant way where in, the data is filtered as and when the multiselect checkbox is checked and not collectively on okbutton click. Also the filter remains open when clicked any where outside. Any work around for this.. kindly suggest I've tried many properties for multiselectoption but no luck. 

Angular version - 5
Angular slickgrid version - 1.9.6

Thanks.

**Comment by ghiscoding** [comment]
The team is 1 person... This has been fixed long time ago, however you're using an extremely old version `1.x` which I don't support anymore. You'll need to upgrade to the minimum Angular 7 so that you can use version `2.x` of the lib. 

Also next time, fill in all necessary questions if you don't want the bot to automatically close your issue like it did now. I won't always answer questions that were closed by the bot.
