### ISSUE TITLE
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[LocalizeRouterService]

### ISSUE THREAD

**Issue by AbdoHesham** [ghiscoding/Angular-Slickgrid#487]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9     | 
| TypeScript              |3.4.5       | 

### Expected Behavior
 itried this npm install --save localize-router
and not working

### Possible Solution
this bug habbened because this files LocalizeRouterService

**Comment by ghiscoding** [comment]
Wow even after 2 closed issues by the bot, I thought you would have understood that you need to fill in the required fields... which you still did not... oh well

But seriously your question should be asked on Stack Overflow not here. Your problem has nothing to do with the lib, unless proven otherwise. I strongly suggest you to read the [HOWTO](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step) or clone the [angular-slickgrid-demos](https://github.com/ghiscoding/angular-slickgrid-demos) repo to get started. 

Again please ask on Stack Overflow, not here.

**Comment by AbdoHesham** [comment]
ok thank you mr.ghislain

‫في الثلاثاء، 9 يونيو 2020 في 3:35 ص تمت كتابة ما يلي بواسطة ‪Ghislain B.‬‏
<‪notifications@github.com‬‏>:‬
