### ISSUE TITLE
How to use SelectAllCheckbox to check/Uncheck all rows if pagination is enabled?

### ISSUE THREAD

**Issue by gauravrane89** [ghiscoding/Angular-Slickgrid#508]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 9.1.0        | 
| Angular-Slickgrid | 2.18.7        | 
| TypeScript        | 3.8.3        | 
| Operating System  | Windows 10       | 
| NPM/Node/Yarn     | v12.14.1        | 

### Context or Topic 
SelectAllCheckbox to check/Uncheck 

### Expected Behavior
Once Select all checkbox is clicked all the rows should be checked if pagination is enabled.

### Current Behavior
Once Select all checkbox is clicked only rows in the current page are getting checked.

### Possible Solution
Make them select all in paginated view also

**Comment by ghiscoding** [comment]
Row Selection with Pagination is only for current page and it's by design, same goes for export data as well. If you want to select everything then you have 2 options increase the page size or disable pagination, again it's by design and there's no way to know what's in next page. This is also a core lib thing (SlickGrid), Angular-Slickgrid is just a wrapper on top of SlickGrid
