### ISSUE TITLE
custom backend loader

### ISSUE THREAD

**Issue by projectX21** [ghiscoding/Angular-Slickgrid#524]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | x.y        | 
| Angular-Slickgrid | x.y        | 
| TypeScript        | x.y        | 
| Operating System  | x.y        | 
| NPM/Node/Yarn     | x.y        | 

### Context or Topic 

I'm searching for a replacement of UI-Grid for Angular 1.x, since we are upgrading to Angular 10. This is the best grid I've found so far, really great work! As a beginner I have one question:
It's mentioned in the readme, that one can implement his one backend service. This in case is needed for my project, because we do server-side pagination, filtering and sorting, but in a custom format (neither odata nor graphQL).
But i havn't found any example for that. Did I miss it in the wiki?

In our UI-Grid project we had the following procedure:
There were onSortChanged/onPaginationChanged/onFilterChanged functions, which contains all the needed data to create the custom queries. In those functions we called the backend with our formatted queries to fetch the new data.

I think in this grid the procedure is a bit different. You have the prefabricated services for OData and GraphQL which act more or less the same way? On any change a new request will be fired in the specified format.

What should I exactly do, if I need a new Service for a custom query format?

**Comment by ghiscoding** [comment]
Yes you can add a different Custom Backend Service and Pagination as it is shown in this [Example](https://ghiscoding.github.io/Angular-Slickgrid/#/swt) that was created by another user (for an Oracle DB if I remember correctly). The code for that example all have the `swt` prefix and I think this [swt-common-grid.component.ts](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/swt-common-grid.component.ts) is the Backend Service one.

To create your own Custom Backend Service, I suggest you take the code of the [GraphqlService](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/graphql.service.ts) and you rewrite the internal of each methods. The thing to remember is that you have to implement the `BackendService` as defined in the GraphqlService (`export class GraphqlService implements BackendService`). 

You typically want to implement your service following these TypeScript interfaces
- [backendService.interface.ts](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/backendService.interface.ts)
- [backendServiceApi.interface.ts](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/backendServiceApi.interface.ts)
- [backendServiceOption.interface.ts](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/backendServiceOption.interface.ts)

At the end of it, you'll have a Custom Backend Service that will be instantiated just like the GraphQL or OData that I've created, it should look similar to this
```ts
this.gridOptions = {
      backendServiceApi: {
        service: new YourCustomBackendService(),
        options: {
          // custom service options that extends "backendServiceOption" interface
        },
        preProcess: () => !this.isDataLoaded ? this.displaySpinner(true) : '',
        process: (query) => this.getCountries(query),
        postProcess: (result) => {
          this.displaySpinner(false);
          this.isDataLoaded = true;
        }
      } as YourCustomBackendServiceApi
};
```

If you need to reference your Service for other purposes then you better instantiated in a separate variable and then just pass it to the `service` property of the `backendServiceApi`.
```ts
class MyComponent {
myCustomService = new YourCustomBackendService();

gridInit {
  this.gridOptions = {
      backendServiceApi: {
        service: this.myCustomService,
        // ...
      } as YourCustomBackendServiceApi
  };
}
```

If your Service is for a well known DB or API framework, then it might be possible to add your Service to the lib itself, however probably better to wait for the next major version of Angular-Slickgrid that will use a new monorepo lib [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal), since that will be a monorepo people will have the ability to use and download only what they need (which is not currently the case). More info [here](https://github.com/ghiscoding/Angular-Slickgrid/releases) (read the section "What's coming in the Future (much later in the year)"), the [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) lib is nearly all done but the next step, which will be long, is to rewrite Angular-Slickgrid to use it... anyway long story short, if you follow everything I wrote, it should also work with next major version and you could possibly contribute to the project as well if you wish to.

I'll turn this into a Wiki

**Comment by projectX21** [comment]
Thank you very much, I will try it! 
I think it would be very nice if you could create a minimal example how to do it,  espacially for newcomers. Maybe which results in a very simple api fetch like : GET <url>?field1=a&field2=b&limit=10&offset=20. I think this is a very common approach for the start of projects which don't use GraphQL nor OData.
I would appreciate it a lot!

**Comment by ghiscoding** [comment]
I seriously have no time to add such demo, I'm not even using Angular for the past couple months, but again that [Example](https://ghiscoding.github.io/Angular-Slickgrid/#/swt) with the `swt` that I referenced earlier is using this technique of creating a custom backend service so you should take a look at it. 

I spent few thousand hours for the past 3 years on this library, it's time for me to step back and let others contribute, that could be a contribution and I'd be happy to get a PR for this.

The question was answered so I'll close this.
