### ISSUE TITLE
Generate odata query without updateFilters method

### ISSUE THREAD

**Issue by meta-akshita-agrawal** [ghiscoding/Angular-Slickgrid#533]
Hey @ghiscoding Is there a way to build odata query by passing custom filters (CurrentFilter[]) and not manipulate dataset
I tried this 
`this.grid.backendService.buildQuery({filteringOptions: customFilters})`

but this won't work. So I added this before building the query

`this.grid.filterService.updateFilters(customFilters, true);
this.grid.backendService.buildQuery({filteringOptions: customFilters})`

and then it started working but apparently updateFilters updates the dataset which I don't want I just want to generate an OData query with those filters

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | x.y        | 
| Angular-Slickgrid | x.y        | 
| TypeScript        | x.y        | 
| Operating System  | x.y        | 
| NPM/Node/Yarn     | x.y        |

**Comment by ghiscoding** [comment]
All the info on how to use the OData Service is in the [Wiki - OData](https://github.com/ghiscoding/Angular-Slickgrid/wiki/OData). You cannot create your own custom `buildQuery` and `updateFilters`, you're completely bypassing the lib and by doing so you're bypassing how the lib uses the Filters. 

If you want to modify the OData query, you might be able to change it from the `process` callback (**after** you get the query returned from the OData Service, don't do it before because you'll be bypassing the lib and that is bad). Perhaps something like this
```ts
initGrid() {
  this.gridOptions = {
    backendServiceApi: {
        service: new GridOdataService(),
        process: (query) => this.getCustomerApiCall(query),
  };
}

// Web API call
getCustomerApiCall(odataQuery) {
   // do your change here then call the Http Service with your updated query
   return this.http.get(`/api/getCustomers?${odataQuery}`).toPromise();
}
```

I have to say it again.. **PLEASE** use Stack Overflow for such type of questions. 
I don't have time to answer all of these questions, which I got a few today (not just from you). Many other users can help on Stack Overflow. I don't personally use the OData anymore, we only did 1 project with it and that was long time ago.

If you think you have some instructions that can be useful in the OData Wiki then please let me know and I can update the Wiki... apart from that please use Stack Overflow.
