### ISSUE TITLE
Not able to generate Angular build due to ngx-translate errors

### ISSUE THREAD

**Issue by mvgadagi** [ghiscoding/Angular-Slickgrid#575]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 8.3.22   | 
| Angular-Slickgrid   | ^2.17.10 | 
| TypeScript              | ~3.5.3    | 

### Describe the Bug

From recently we started receiving errors while generating the dist of the project and errors as follow

```ERROR in ../node_modules/@ngx-translate/core/lib/translate.directive.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     set translate(key: string);
           ~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.directive.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     set translateParams(params: any);
           ~~~~~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:49:9 - error TS1086: An accessor cannot be declared in an ambient context.

49     get onTranslationChange(): EventEmitter<TranslationChangeEvent>;
           ~~~~~~~~~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:56:9 - error TS1086: An accessor cannot be declared in an ambient context.

56     get onLangChange(): EventEmitter<LangChangeEvent>;
           ~~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:63:9 - error TS1086: An accessor cannot be declared in an ambient context.

63     get onDefaultLangChange(): EventEmitter<DefaultLangChangeEvent>;
           ~~~~~~~~~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:67:9 - error TS1086: An accessor cannot be declared in an ambient context.

67     get defaultLang(): string;
           ~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:68:9 - error TS1086: An accessor cannot be declared in an ambient context.

68     set defaultLang(defaultLang: string);
   91m        ~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:72:9 - error TS1086: An accessor cannot be declared in an ambient context.

72     get currentLang(): string;
           ~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:73:9 - error TS1086: An accessor cannot be declared in an ambient context.

73     set currentLang(currentLang: string);
           ~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:77:9 - error TS1086: An accessor cannot be declared in an ambient context.

77     get langs(): string[];
           ~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:78:9 - error TS1086: An accessor cannot be declared in an ambient context.

78     set langs(langs: string[]);
           ~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:82:9 - error TS1086: An accessor cannot be declared in an ambient context.

82     get translations(): any;
           ~~~~~~~~~~~~
../node_modules/@ngx-translate/core/lib/translate.service.d.ts:83:9 - error TS1086: An accessor cannot be declared in an ambient context.

83     set translations(translations: any);
           ~~~~~~~~~~~~
```

### Steps to Reproduce

npm install
ng build --prod

### Expected Behavior

Dist files should be generated successfully

### Code Sample

My package.json
```
   "@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@ckeditor/ckeditor5-build-inline": "^18.0.0",
    "@ng-bootstrap/ng-bootstrap": "^5.1.5",
    "@ng-select/ng-option-highlight": "0.0.4",
    "@ng-select/ng-select": "^3.7.1",
    "angular-slickgrid": "^2.17.10",
    "angular2-draggable": "^2.3.2",
    "bootstrap": "^4.4.1",
    "exceljs": "^1.12.0",
    "file-saver": "^2.0.2",
    "ionicons": "^4.6.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.28",
    "ng5-slider": "^1.2.4",
    "ngx-cookie-service": "^2.3.0",
    "ngx-filesaver": "^8.1.0",
    "ngx-typeahead": "^6.2.0",
    "rxjs": "~6.4.0",
    "stream": "0.0.2",
    "timers": "^0.1.1",
    "tslib": "^1.10.0",
    "xml2js": "0.4.19",
    "zone.js": "~0.9.1"
```

**Comment by ghiscoding** [comment]
That is an error with your TypeScript, it has nothing to do with the lib itself. It looks like you're possibly using TypeScript version `3.7` (even though you wrote `3.5`) and if you do then you might get this error. 

Basically I posted the same kind of error on another lib `NestJS` and at the time it was due to `NestJS` using TypeScript `3.5` while I had `3.7` on my local. You can see more info in that issue I've opened on [NestJS - issue](https://github.com/nestjs/nest/issues/3513) and has you can see it's the same kind of error
```shell
node_modules/@nestjs/common/http/http.service.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.
13     get axiosRef(): AxiosInstance;
           ~~~~~~~~
```

Again it has nothing to do with Angular-Slickgrid, most probably is a problem with `ngx-translate` and/or which version of TypeScript you're using. 

Also note that even if `ngx-translate` is optional in Angular-Slickgrid, it still has to download it and it will be part of your `node_modules` when you run an `npm install`, that is because in the lib I'm using `@Optional() private translate: TranslateService` and that makes it optional but for that to work it still must be part of the `node_modules` because it has the `import { TranslateService } from '@ngx-translate/core';` on top of each of the files. I believe (I'm guessing) that any optional services will be dropped by the tree shacking only after the prod build... I think you don't have to refer to the correct version of `ngx-translate` in your `devDependencies` but you could try that too (you can refer to the [ngx-translate - installation](https://github.com/ngx-translate/core#installation) wiki to know which one to use depending on your Angular version).

**Comment by mvgadagi** [comment]
Thanks @ghiscoding for the response , I regularly follow your updates and unluckily I started noticing this error after the merge of peer dependencies for ngx-translate, Initially I thought I can upgrade my Typescript unluckily still my massive Angular app struck with 8.3.xx , Is there anything you can suggest me?

**Comment by ghiscoding** [comment]
You should update to latest Angular-Slickgrid and like I said the [Angular-Slickgrid-Demos with Locales](https://github.com/ghiscoding/angular-slickgrid-demos/tree/master/bootstrap3-demo-with-locales) does work and that demo is with Angular 9. I know Angular fixes the TypeScript version on every release, so you shouldn't play with that. The demo works as expected so I'm not sure why it doesn't on your side. You still didn't say if you do use `ngx-translate` or not though, I assumed that you don't since I didn't see it in your list of packages

There isn't much I can suggest apart from trying the [Angular-Slickgrid-Demos with Locales](https://github.com/ghiscoding/angular-slickgrid-demos/tree/master/bootstrap3-demo-with-locales) and/or ask questions about Angular and `ngx-translate` on Stack Overflow.

**Comment by mvgadagi** [comment]
Okay sure, I will  try these two things and keep you posted my status in another 12 hours , so it may help other to understand what is causing these kind of errors

1.Delete node_modules and try fresh npm install
2.Upgrading Slickgrid to 2.21.3
3.Add ngx-translate to devDependencies and verify

Regards,
MG

**Comment by mvgadagi** [comment]
I have tried deleting the node_modules and did a fresh install tough I am not using ngx-translate

Updates 1) Delete node_modules and try fresh npm install
```
ERROR in node_modules/angular-slickgrid/app/modules/angular-slickgrid/components/angular-slickgrid.component.d.ts:8:34 - error TS2307: Cannot find module '@ngx-translate/core'.

8 import { TranslateService } from '@ngx-translate/core';
                                   ~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-slickgrid/app/modules/angular-slickgrid/components/slick-pagination.component.d.ts:2:34 - error TS2307: Cannot find module '@ngx-translate/core'.
```

**Comment by mvgadagi** [comment]
@ghiscoding  When I did the `npm i @ngx-translate/core` Still I was facing the same issue with build, but now after reading through documentation of ngx-translate/core I found that below are the version compatible 


Angular | @ngx-translate/core | @ngx-translate/http-loader
10 | 13.x+ | 6.x+
9 | 12.x+ | 5.x+
8 | 12.x+ | 4.x+
7 | 11.x+ | 4.x+

So I manually added    ` "@ngx-translate/core": "12.0.0",` and my issue resolved and build is successful

**Comment by mvgadagi** [comment]
@ghiscoding Do you think you can solve the issue globally by updating the https://github.com/ghiscoding/Angular-Slickgrid/pull/567 or may be you add the note point to users based on the Angular version 🤔

**Comment by ghiscoding** [comment]
We could possible add a note to the README in the [Compatibility](https://github.com/ghiscoding/Angular-Slickgrid#angular-compatibility) list section. That would be really great if you could contribute to the lib by modifying the README with the steps you followed. Mind doing a quick PR? You could do it directly from GitHub website too

**Comment by mvgadagi** [comment]
> We could possible add a note to the README in the [Compatibility](https://github.com/ghiscoding/Angular-Slickgrid#angular-compatibility) list section. That would be really great if you could contribute to the lib by modifying the README with the steps you followed. Mind doing a quick PR? You could do it directly from GitHub website too... and/or update the [HOWTO Steps by Steps - Wiki](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step)

Okay sure @ghiscoding I will do a PR to update the README

**Comment by mvgadagi** [comment]
@ghiscoding I have made a PR https://github.com/ghiscoding/Angular-Slickgrid/pull/576 , Please review !!
