### ISSUE TITLE
excel-builder-webpacker GPLv3 license

### ISSUE THREAD

**Issue by arturtv** [ghiscoding/Angular-Slickgrid#579]
## General Topic
First want to thank you for the great work.

I have a question regarding the license, the library itself is MIT, however it looks like it has dependency of
"excel-builder-webpacker": "^1.0.6",
https://github.com/ghiscoding/Angular-Slickgrid/blob/master/package.json#L104

which is marked as GPLv3: https://www.npmjs.com/package/excel-builder-webpacker/v/1.0.6

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 9.0        | 
| Angular-Slickgrid | 2.x        | 
| TypeScript        | 3.6        | 
| Operating System  | 1.0        | 
| NPM     | 1.0        | 

### Context or Topic 
Not really expert however it seems that it forces to use Angular-Slickgrid as GPLv3 due to dependency

### Expected Behavior
maybe to move to more permissive libraries or make excel-builder-webpacker optional dependency, anything that will allow to avoid GPLv3

### Current Behavior
Excel export is one of the optional functionalities that probably many do not require

**Comment by ghiscoding** [comment]
The lib is [excel-builder](https://github.com/stephenliberty/excel-builder.js/tree/master/License) and for some reasons it seems to be having 2 licenses MIT is there as well

**Comment by arturtv** [comment]
agree,  it is confusing as:
 1. the most restrictive is GPLv3 and 
 2. npm repository has it under GPLv3.

**Comment by ghiscoding** [comment]
I'm assuming NPM shows it as GPLv3 because it auto-detect it by finding it in the project.
There's not much else that I can do on this, `excel-builder-webpacker` is a fork that I own which is a fork of `excel-builder-webpack` which is itself a fork of `excel-builder` (the final lib) and that lib is out of support but again it has both licenses MIT is included in it. Why does the lib have both? I don't know but there's nothing I can do about that, so I'm thinking about closing your issue since there's no real action I can do, I would say it already has the MIT license anyway.

**Comment by arturtv** [comment]
thanks for update, 

Both the bower.json and package.json for the main package excel-builder-webpack declare the project's license to be only GPLv3.
https://github.com/hohiep102/excel-builder.js/blob/master/bower.json#L20
https://github.com/hohiep102/excel-builder.js/blob/master/package.json#L20

The upstream project seems to be have code from various sources too:
https://github.com/hohiep102/excel-builder.js/blob/master/dist/excel-builder.dist.js#L3173-L3199

Some of which is not clearly disclosed up front by the project.

Agree that you can not change the license of dependencies, however the dependency forces slick-grid to inherit more restrictive license due to that dependency, and probably there are two paths:
1. make it more transparent for its users as an investigation of the licenses could be interpreted the other way and lead to legal consequences to its users that are not aware of the problem. 
2. make the dependency optional for users that do not need that

feel free to resolve the issue however it would be great that all the effort that you put to remain fully under MIT as you intended.

**Comment by ghiscoding** [comment]
Closing since there isn't much I can do here, and I won't find alternative either, I'm not interested in spending few hundred of hours that I had spent on adding the Excel Export feature. However if you are concerned then I suggest you to simply disable the Excel Export so that you won't use that piece of code.

**Comment by ghiscoding** [comment]
the next `major 3.x` of Angular-Slickgrid is out and both Export Services are optional, you can choose which one to install (so you can now exclude the Excel Export if the license is an issue). See the [Release](https://github.com/ghiscoding/Angular-Slickgrid/releases) section
