### ISSUE TITLE
Group Selection

### ISSUE THREAD

**Issue by atuljain707** [ghiscoding/Angular-Slickgrid#583]
Hi,

### Motivation / Use Case
When we apply the grouping with check box selection, there should be checkbox available for selecting the group also.

### Expected Behavior
When we select the checkbox, all entries under that group will be selected including sub-group entries if any.

### Other Information

NONE

**Comment by atuljain707** [comment]
I tried the examples given for normal slick-grid but didn't get the checkbox for grouping. and didn't find working example for this.

**Comment by ghiscoding** [comment]
If you're talking about this [Example](http://6pac.github.io/SlickGrid/examples/example-grouping-checkbox-row-select.html) it's not directly in Angular-Slickgrid because there was few issues [here](https://github.com/6pac/SlickGrid/issues/165) and so I won't add a demo for that. All core SlickGrid plugins are part of Angular-Slickgrid, you'll have to find how to replicate the example yourself
