### ISSUE TITLE
Row Detail Callback OnModelSet

### ISSUE THREAD

**Issue by TryAndErr0r** [ghiscoding/Angular-Slickgrid#586]
### Motivation / Use Case
Currently when using the DetailRow feature the model of the DetailRow is automagically inserted into the model Property of the DetailRowComponent. 
This prevents me to handle the selected value before showing it. Like swaping template on diffrent model types or prepairing animation in viewmodel. 

### Expected Behavior
An interface ISlickGridDetailRow with an function OnData which all DetailRow component needs to extend. SlickGrid calls this funktion when passing the model to the item. 

### Other Information
I read the wiki, but there is no note about how the model is placed into the detail view component. I dont know if i overread something or if it is realy not mentioned at all. 

Also i tried fiddling in the callback myself but got stuck on the RowDetailViewExtension.prototype.renderViewModel function.

    RowDetailViewExtension.prototype.renderViewModel = function (item) {
        var _this = this;
        var containerElements = document.getElementsByClassName("" + ROW_DETAIL_CONTAINER_PREFIX + item[this.datasetIdPropName]);
        if (containerElements && containerElements.length > 0) {
            var componentOutput = this.angularUtilService.createAngularComponentAppendToDom(this._viewComponent, containerElements[containerElements.length - 1], true);
            if (componentOutput && componentOutput.componentRef && componentOutput.componentRef.instance) {
                // pass a few properties to the Row Detail template component
                Object.assign(componentOutput.componentRef.instance, {
                    model: item,
                    addon: this._addon,
                    grid: this.sharedService.grid,
                    dataView: this.sharedService.dataView,
                    parent: this.rowDetailViewOptions && this.rowDetailViewOptions.parent,
                });
                var viewObj = this._views.find(function (obj) { return obj.id === item[_this.datasetIdPropName]; });
                if (viewObj) {
                    viewObj.componentRef = componentOutput.componentRef;
                }
                return viewObj;
            }
        }
        return null;
    };
I did just paste  ' componentOutput.componentRef.SetModel(item); ' after Object.assign and this seems to work as i intended

**Comment by ghiscoding** [comment]
Sorry but I don't understand what your question or use case is, all the info you need is mostly all in the Wiki. If you want more info, you can take a look at the [rowDetailView.interface.ts](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/rowDetailView.interface.ts), if you want to see how this is all connected then look at the [rowDetailViewExtension.ts](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts). Row Detail is an extra plugin from the SlickGrid core lib, this plugin is [RowDetailView.js](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowdetailview.js), all the docs about the plugin is directly in the file, the way that is used in Angular-Slickgrid is simply to use the core plugin and to convert an Angular component into pure html/js so that the core plugin can read it (I guess that is what you'll call the auto-magic) and that is done through [createAngularComponent](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/angularUtil.service.ts#L13). 

Perhaps what you might not fully understand is that Angular-Slickgrid is a wrapper on top of SlickGrid which itself is an old jQuery lib which knows nothing about Angular, We just simply point to an Angular component, convert it to regular html/js and that is all it does. The Row Detail was designed to simply add provide more detail about the clicked row, for example showing the full info/bio of a user when clicking on the row (hence why it was named Row Detail View).

Take a look at the [Row Detail Panel Example](https://6pac.github.io/SlickGrid/examples/example16-row-detail.html) from the core lib, you might understand more how this all works.

You should probably ask these kind of question on Stack Overflow.

**Comment by TryAndErr0r** [comment]
Yeah i was to quick when posting this. Sorry for that. Still my idea was somekind of event for the detailrowViewModel so it itself can prepaire for showing information.

**Comment by ghiscoding** [comment]
All the available events are [there](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/rowDetailView.interface.ts#L88) there's nothing to add and if you still think there's other event(s) that can be added then you'll need to add it first to the [6pac/SlickGrid](https://github.com/6pac/SlickGrid) fork, that is the starting point. 

I am closing since I don't see anything for me to do here, if you still think that you can improve this plugin then please create a Pull Request.
