### ISSUE TITLE
closeOnSelect: false flatpickroption is not working

### ISSUE THREAD

**Issue by gvrai** [ghiscoding/Angular-Slickgrid#615]
### Motivation / Use Case

If someone wants that calender is remain open after select date in calender that feature is not supported by slickgrid but as slickgrid is using third party api flatpickr that supports that feature.

### Expected Behavior

 const pickerOptions: FlatpickrOption = {
        defaultDate: this.defaultDate as string,
        altInput: true,
        altFormat: outputFormat,
        dateFormat: inputFormat,
        closeOnSelect: true,
        wrap: true,}
You should not declare closeonSelect :true rather than that it should be default which is false or someone use closeOnSelect:false in slickgrid(editoroptions) that is support there.

### Other Information

kindly update in dateEditor.ts file and resolve this issue asap that will be really helpful.

**Comment by ghiscoding** [comment]
>  resolve this issue asap that will be really helpful.

Seriously the way you write your issue is quite insulting, you should understand that this is an Open Source project which you are **not** paying a penny for and you're asking me (who already spent the past 3 years working thousand of hours on the lib) to fix this for you for free ASAP??? You should try to be a bit more friendly when asking such question... and really this is really just a a **Question not an Issue**, you can change most of the options yourself with `editorOptions` or `filterOptions` depending on what you use. You can see this in this [Wiki - Editor Options (MultipleSelectOption interface)](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Editors#editor-options-multipleselectoption-interface) or direcly in code on this [Example 4](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-clientside.component.ts#L139)

Something like this should work
```ts
filter: {
          model: Filters.compoundDate,
          // override any of the Flatpickr options through "filterOptions"
          // please note that there's no TSlint on this property since it's generic for any filter, so make sure you entered the correct filter option(s)
          filterOptions: { closeOnSelect: false } as FlatpickrOption
        }
```

Perhaps you should also try to Contribute instead of asking your question the way you did

If you don't understand why I'm being insulted, the word **ASAP** is the worst part of your message... I don't work for you and you are using this lib for free. Don't you know what Open Source mean?? Perhaps I should post a portion of the [MIT License](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/LICENSE) might help to make it more clear.
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED

Try to be more friendly next time and please consider asking such question on Stack Overflow.
