### ISSUE TITLE
Mousewheel event in row detail

### ISSUE THREAD

**Issue by meta-akshita-agrawal** [ghiscoding/Angular-Slickgrid#618]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 9.0        | 
| Angular-Slickgrid | 2.17        | 
| TypeScript        | 3.7        | 

### Context or Topic 

Hi Author,

Thanks for making such a great library :). I am reporting the issue for the row detail feature in your library. I am unable to scroll row detail div through the mouse wheel. Once scrolled down(dragging with the pointer), it moves up with the mouse wheel but never down. 
I am not sure if you have a solution for this or even this issue is any priority for you but I have tried everything and unable to get hold of this. If you have any workaround, it will be a big help.
The last option is that I apply a third party jquery plugin on the row detail div.

PS: Reproducible in the library itself

Steps to reproduce :
1. Change row count from 9 to 5 on this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/624ac682155d6e2badded38348d1dd5ab5def4bc/src/app/examples/grid-rowdetail.component.ts#L33)
2. Go to the Row detail page, open any of the row detail
3. Try to scroll div with mouse wheel event

### Expected Behavior

When the pointer is in the row detail area, the mouse wheel should scroll the row detail div rather than the table div

### Possible Solution

What I realized that when I inspect and remove the last 2 mouse wheel slick grid events, it starts working as expected. Maybe these 2 events are preventing the inside mouse wheel event

![image](https://user-images.githubusercontent.com/41181785/97581655-d336fc00-1a1a-11eb-8d52-346f51ffd3e8.png)

**Comment by ghiscoding** [comment]
That is most probably an issue in the core lib [6pac/SlickGrid](https://github.com/6pac/SlickGrid) which will have to addressed in that fork not in Angular-Slickgrid. You should try to see if you can replicate the issue in the core lib [Example - Row Detail](http://6pac.github.io/SlickGrid/examples/example16-row-detail.html), if it's reproducible there then it's in the core lib, if not then it might be in Angular-Slickgrid (but I doubt it)

**Comment by meta-akshita-agrawal** [comment]
No, it's not reproducible in 6pac/Slickgrid
![ezgif com-gif-maker](https://user-images.githubusercontent.com/41181785/97589575-ad622500-1a23-11eb-8cb7-451f6646f2a5.gif)

**Comment by ghiscoding** [comment]
I seriously have no time to look into this, so I would require your help in troubleshooting the issue. It might be something in the CSS styling (SASS in Angular-Slickgrid).

**Comment by meta-akshita-agrawal** [comment]
Ok I will look into it and let you know If I find something

**Comment by ghiscoding** [comment]
The main difference against the core lib is that I created my own SASS styling in Angular-Slickgrid, sometime it's not fully in sync with the core lib on the styling side. You can see the full styling on this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/styles/slick-plugins.scss#L1082) of `slick-plugins.scss` file and you can also compare the styling directly in chrome. The other place to possibly look into would be the implementation of Row Detail in Angular-Slickgrid via the [rowDetailViewExtension.ts](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/extensions/rowDetailViewExtension.ts), it's different compare to the core because it's specific code to load an Angular component dynamically. 

I would think the issue is possibly in the SASS

**Comment by meta-akshita-agrawal** [comment]
Thanks, let me dig into it.

**Comment by meta-akshita-agrawal** [comment]
Also, wanted to know if this is any other scroll plugin in the detail view? Because the outside scroll looks like a browser scroll and the internal one looks like some another. In the core lib, it seems that both scroll bars are browsers. 
Just a thought, that the scroll plugin may have created this problem.
Can I get hold of that part of the code?

**Comment by ghiscoding** [comment]
I don't know why that is different, but again I think it might be CSS styling but I don't know more than that. I already gave you the 2 files to look into the SASS file or the `rowDetailViewExtension.ts`

**Comment by ghiscoding** [comment]
I strongly believe it's CSS and so I changed the [Angular-Slickgrid - Row Detail](https://ghiscoding.github.io/angular-slickgrid-demos/#/rowdetail) demo and posted a question on Stack Overflow [here](https://stackoverflow.com/questions/64597105/scrollbar-not-styled-properly-and-not-working-with-mouse-wheel), you can refer to that SO and maybe upvote the question. Hopefully someone can answer just by looking at the live demo.

**Comment by meta-akshita-agrawal** [comment]
Thanks a lot.

**Comment by ghiscoding** [comment]
Pushed a patch for this under the new release [v.2.23.x](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.23.0). I say it's a patch since a better implementation would be to add a new flag in SlickGrid (core) to disable the mousewheel scroll handler (which is what causes this issue and was answered in the SO question), right now I'm only importing the `jquery.mousewheel.js` if your grid uses the frozen (pinning) feature but it's not a full fix because as soon as it loaded once it stays loaded and that will still cause the problem.

So anyway, the patch is available under the new release [v.2.23.x](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.23.0)

If you like the lib and haven't already upvoted, please do so ⭐ 
Thanks

**Comment by ghiscoding** [comment]
There is now a new grid option flag called `enableMouseWheelScrollHandler` in the SlickGrid core lib which you can use to enable/disable the mousewheel scroll, it will automatically enable the flag when detecting the grid as being a frozen grid, any other grid will expect this flag to be disabled and won't interfere with the Row Detail plugin. There was 2 PRs made to fix this, the 1st PR was more of a temporary fix while the the 2nd one is a permanent fix.
