### ISSUE TITLE
A memory leak in Angular-slickgrid.js causing an event handler to fire multiple times causing typing delay in my app

### ISSUE THREAD

**Issue by tannenbaums** [ghiscoding/Angular-Slickgrid#635]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 10.1.5       | 
| Angular-Slickgrid   | 2.23.0       | 
| TypeScript              | 4.0.3        | 

### Describe the Bug
Angular-slickgrid adds a keydown listener to the document
document.addEventListener('keydown', (e) 
but because there's a leak, this listener is fired as many times as there are instances in memory, causing a delay in 
my app as the user types in the input boxes. The more the user users the app the more instances in mem the more
delay is accumulated.

### Steps to Reproduce
If you go to the Angular-slickgrid demo site and toggle the examples let's say 30 times and take a heap snapshot you'll see that angular-slickgrid is there many times...put a breakpoint as in the image below and start typing into any column filter and you'll see it hit as many times as there are instances...

![image](https://user-images.githubusercontent.com/38888997/99600750-10fcc400-29cc-11eb-9050-5fad9b8dd486.png)

### Expected Behavior
No leak

### Current Behavior
Yes leak

**Comment by ghiscoding** [comment]
For reference, I wrote this earlier

> Ok I think I know what the issue is, all the SlickGrid external plugins, like this cell copy manager is, have to be registered/loaded via `registerPlugin()` but I forgot to use the `unregisterPlugin()` when destroying all of these plugins. I need to add a `dispose` or `destroy` to loop through all loaded plugins in the `ExtensionService` and call that `unregisterPlugin()` on each of them when leaving.
>
> Can you open another issue with the last comment you wrote. This issue is getting way too long and there's something already pushed and released. 
>
> Because of that missing `unregisterPlugin()` it is still a leak indeed, but another issue is better, I'll reference the other issue when doing another PR later

**Comment by ghiscoding** [comment]
oh gosh I learned something new, so I was disposing the plugin correctly but I wasn't removing the event handler properly. 

If I do this
```ts
document.addEventListener('keydown', this.handleKeyDown.bind(this));

// then destroy it
document.addEventListener('keydown', this.handleKeyDown);
```
it won't work because the event listener handler is **not** the same reference even if they point to the same function, simply because it has different binding. However, I think it would work if they both use the same reference `this.handleKeyDown`, but I usually add the `.bind(this)` because I want the global this reference. 

To fix this I actually have to keep an external reference and then use it in both adding/removing
```ts
const handler = this.handleKeyDown.bind(this);
document.addEventListener('keydown', handler);

// then destroy it with the correct reference
document.addEventListener('keydown', handler);
```

wow I really didn't know that it was that specific and I found that out by reading the comments in this [SO Answer](https://stackoverflow.com/a/10444156/1212166), it looks like this plugin and the `Editors.dualInput` are the only 2 places where I didn't do it properly. By doing a quick search in SlickGrid (core), I didn't find any but I would guess that the `unsubscribe` is also sensitive to that and is also why using the `eventHandler.unsubscribeAll()` is always better... which also explains why the reworking the `this.gridObj.onMouseEnter.subscribe` in the `grid-frozen.component.ts` Example was also leaking earlier. Starting to understand all of it now, it's interesting to see how precise this has to be.

**Comment by tannenbaums** [comment]
that's great! just curious I see in a lot of places angular code they do .removeEventListener...?? isn't that an option for you to use?

**Comment by ghiscoding** [comment]
unless Angular has it's own service to deal with `addEventListener` and `removeEventListener` are simple common JavaScript functionalities, nothing fancy there. But anyway, I try to avoid using direct Angular specific code if I can do it in couple lines of code. Why? Because I support 3 libs (Angular-Slickgrid, [Aurelia-Slickgrid](https://github.com/ghiscoding/aurelia-slickgrid/) and [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) which the latter is framework agnostic) and all 3 use a big portion of the same code, so I would rather write 1 simple service that I can reuse in all 3 libs. 

For this particular case, I'm writing a very small (micro) service 
_there's a bit more type checking than that but it's the general idea shown below_
```ts
export class BindingEventService {
  private _handlers: any;

 bind(element, event, listener) {
   this._handlers.push(element, event, listener);
   element.addEventListener(element, event, listener);
}

unbindAll() {
  for (const handler of this._handlers) {
    const { element, event, listener } = handler;
    element.removeEventListener(event, listener);
  }
}
```
sweet and simple, then when I want to use it, I just create a new instance of the service and when I can the `unbindAll` it's specific to that component
```ts
this.bs = new BindingEventService();

  hook() {
    this.bs.bind(document.body, 'keydown', () => /** do something */);
  }

  destroy() {
    this.bs.unbindAll();
  }
}
```
That's it, easy peasy and that leaves no detached or leaking events since the event listener/handler is properly referenced.

---

Also to go back on Slickgrid-Universal, since I mentioned it couple times, that is mostly where I do the work lately and that is a monorepo lib that will eventually be used with the next planned major version of Angular-Slickgrid 3.x. Since Slickgrid-Universal is a monorepo and framework agnostic (that was the goal when I wrote it) and has 80% of the same code from all 3 libs, I will drop that 80% shared code from Angular-Slickgrid and reference the monorepo code of Slickgrid-Universal because it's not very efficient to service 3 libs every time I add/fix new features/bugs (for example all the Services are common code since there's no framework specific code in there, hence why I'm writing this new `BindingEventService` with regular TS code). This will take few months to achieve but most of the monorepo is ready, I just need to eventually start removing code from Angular-Slickgrid/Aurelia-Slickgrid.

**Comment by tannenbaums** [comment]
cool! So when can we have this goodness?

**Comment by ghiscoding** [comment]
now released under [version 2.23.2](https://github.com/ghiscoding/Angular-Slickgrid/releases)

**Comment by tannenbaums** [comment]
great!! thank you so much! I will test it out when I get a chance...

**Comment by tannenbaums** [comment]
This indeed fixes my typing speed issue, thank you so much for all your help and patients with me :)
just as a side note: I still need to use the slickgrid version from the zip file if I don't want my components leaking...just something to keep in mind... Thank you!!
