### ISSUE TITLE
Header and preHeader are misaligned

### ISSUE THREAD

**Issue by slayer303** [ghiscoding/Angular-Slickgrid#649]
Hi ,
Before, I want to thank you for lib it's really a very complete one.

## General Topic

 Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8.1        | 
| Angular-Slickgrid | 2.24.1        | 
| TypeScript        | x.y        | 
| Operating System  | Windows10        | 
| NPM/Node/Yarn     | x.y        | 

### Expected Behavior
When I added a border to columns and working with "Column Span & Header Grouping" I can see that the pre-header and the header are misaligned as shown in the snapshot bellow.
### Current Behavior
The width of preheader column is incorrect (even if you don't add the border and sum widths the sum is not correct.)
![widthMisaligned](https://user-images.githubusercontent.com/3456714/102065412-d0407100-3df8-11eb-8747-2b990cb126ab.png)
it all sub columns including padding
### Possible Solution
I think it's related to pre-header width calculation if it's englobe more than 1 column

**Comment by ghiscoding** [comment]
The pre-header are calculated width, I've seen this and I added a grid option `frozenHeaderWidthCalcDifferential` for that reason which you can see it used in the width calculation [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/groupingAndColspan.service.ts#L128), the default in the global config is set to 1 but if that doesn't work for you try 0. 

That might not fix your problem entirely though, you might still have some offset issues on some of the columns and if that is the case then you're out of luck, I couldn't figure out a better way to fix this (mostly because it's a calculated width.

If you find a better way to fix it then please create a Pull Request, else I will close this issue as "Can't fix" sorry

**Comment by slayer303** [comment]
Yes that worked like a charm! with "0" 
thanks very much 👍

**Comment by ghiscoding** [comment]
Glad to know that works, I might change the global config back to 0 then. 

You can also upvote ⭐ if you haven't already 😉 
Cheers
