### ISSUE TITLE
Tree Data row collapse does not work with backendApi and localFilter = false

### ISSUE THREAD

**Issue by chitwank-asu** [ghiscoding/Angular-Slickgrid#658]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 11.0.4       | 
| Angular-Slickgrid   | 2.24.1        | 
| TypeScript              | 4.0.2       | 

### Describe the Bug

The expand and collapse button does not work( as they do in the below demo) when we add backendServiceApi and set backendServiceApi.useLocalFiltering = false
https://ghiscoding.github.io/angular-slickgrid-demos/#/tree-data-parent-child

### Steps to Reproduce

Copy the code of the following demo, but instead of local data use backendServiceApi to load and assign data to the grid with backendServiceApi.useLocalFiltering = false
https://ghiscoding.github.io/angular-slickgrid-demos/#/tree-data-parent-child

On doing so, the collapse and expand icon stop working. They do not hide and show the child rows:
![image](https://user-images.githubusercontent.com/67097952/103653181-2af96280-4f8a-11eb-9949-8f30653ee88e.png)

### Expected Behavior

The expand and collapse icons should work even when the data is loaded from backend and backendServiceApi.useLocalFiltering = false

### Current Behavior

The expand and collapse button does not work when we add backendServiceApi and set backendServiceApi.useLocalFiltering = false
https://ghiscoding.github.io/angular-slickgrid-demos/#/tree-data-parent-child
Error img:
![image](https://user-images.githubusercontent.com/67097952/103653181-2af96280-4f8a-11eb-9949-8f30653ee88e.png)

### Code Sample

```ts
 this.gridOptions = {
      enableTreeData: true, // you must enable this flag for the filtering & sorting to work as expected
      treeDataOptions: {
        columnId: 'client',
        levelPropName: 'indent',
        parentPropName: 'parentId'
      },
      enableFiltering: true,
      enableRowSelection: true,
      backendServiceApi: {
        service: new GridOdataService(),
        ...
        }
    }
```

**Comment by ghiscoding** [comment]
I have no time to investigate this **but** I would say though that if you're trying to use Tree Data with a Backend Service (mainly Pagination), I just **will not** provide support for that. The reason is simple, there's no way to know when and where the Tree might stop/start between pages... so where you using Pagination with your backend service? If the answer is Yes then sorry but I will close this issue as "won't do"

**Comment by chitwank-asu** [comment]
Thanks for your reply. 
Yeah, we are using backend with pagination. So, what solution would you recommend for this? Backend without pagination and local filter - true?

**Comment by ghiscoding** [comment]
`useLocaleFiltering` was only created for Backend Services, it is useful when you want to use GraphQL/OData Service to create the query string for you and retrieve **all** the data once and then use local (in-memory) filtering. That is usually used without Pagination because local filtering assumes you have all the data in memory hence using local (in-memory) filtering and that really means without pagination which is what the [Example 27](https://ghiscoding.github.io/Angular-Slickgrid/#/graphql-nopage) does.

Tree Data just doesn't work with Pagination (that is also true for local in-memory pagination), as a side note that is also true for Grouping as well. What it means is that you need to load all your data and then you'll be able to use Tree Data.
