### ISSUE TITLE
Server-side grouping with paging

### ISSUE THREAD

**Issue by erikcordeiro** [ghiscoding/Angular-Slickgrid#673]
Hi, @ghiscoding.
I'm analyzing a possible use of Angular-Slickgrid in a project, and I'm enjoying what I've seen.
However, a feature that will be required, and I have understood that Angular-slickgrid does not support, is server-side pagination with grouping. I saw the issue #272 and know how difficult it is to implement (but not impossible).
I implemented this same feature in [Treegrid](http://www.treegrid.com/) years ago and I can take a little time to doing this in Angular-slickgrid as a thank for your work.
But I need minimal guidance from you on how I could implement it.
The idea, initially, is to conduct a first query to retrieve the top-most groups. When a group is expanded, perform the equivalent query which can bring other n-levels groups or final records. The number of pages is updated as groups change state (like [this example](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/groupby#angular-group-by-with-paging-example)).
Can you help me?

**Comment by ghiscoding** [comment]
Please fill in the necessary questions the next time to avoid the bot automatically close your issue. 

For your question, it's not supported because the Grouping comes from SlickGrid the core lib itself (not Angular-Slickgrid) and as far as I can see this [Example](http://6pac.github.io/SlickGrid/examples/example-grouping.html) seems to also work with local pagination but I'm not sure I like the experience there (you can give it a try), from what I see the grouping of "Duration 0" is on both page, it seems a bit weird at first glance (I mean I'm confused why they do that and I'm assuming other users will be confused as well), see animated gif below. So the reason of why I'm showing it with local pagination first is because like I said on first paragraph, the Grouping features comes from the core not my lib and if it doesn't work correctly in the core then you might have to change the code in that lib first [6pac/SlickGrid](https://github.com/6pac/SlickGrid) for it to then work in Angular-Slickgrid. 

Then it depends which backend service you're using, if it's the OData then it uses the the `set dataset` [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts#L209) when then call `refreshGridData` [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts#L409), so I don't think the blocker is Angular-Slickgrid, it probably require changes in the core lib first. 

Then the next problem will probably be what you mentioned, which is the problem of "what is on the next/previous page?", Angular-Slickgrid doesn't work with a magic ball of crystal. The way I've designed it is to use SlickGrid [DataView](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js) at all time and when I detect that the backend changed page, I simply the DataView [setItems](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js#L163) function to replace its data and then re-render the grid (basically the DataView gets refreshed and lose data of the previous page), it doesn't keep any reference of any other page than current. 

Just as a reminder, I've wrote this in couple place on the readme but in case you didn't see it or understand it, Angular-Slickgrid is a wrapper on top of the well implemented [SlickGrid](https://github.com/mleibman/SlickGrid) which is a jQuery lib. To support Grouping with Backend Pagination, I have a feeling you'll have to change code in both libs.

I'm not sure which code would need to change but for Grouping in SlickGrid, the Grouping exist in 2 files [slick.groupitemmetadataprovider.js](https://github.com/6pac/SlickGrid/blob/master/slick.groupitemmetadataprovider.js) and [slick.dataview.js](https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js) which uses the `groupitemmetadataprovider`... so as you can see it's not exactly straight forward, the code is in multiple area, it will require some time to analyze and possibly refactor.

![M4lVaA1Ent](https://user-images.githubusercontent.com/643976/104969625-07391200-59b7-11eb-80a6-b9faa9b09bea.gif)

**Comment by ghiscoding** [comment]
I'm going to close this, if you want to discuss further I suggest to use the new [Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions) section which is more appropriate for this kind of subject. Thanks
