### ISSUE TITLE
Add new operator in select of Compound Filter

### ISSUE THREAD

**Issue by audrys** [ghiscoding/Angular-Slickgrid#733]
### Motivation / Use Case

I need to rename selection option in compound filter and add extra one.
### Expected Behavior

I need to set Contains filter to prefix '*b*'
### Other Information

Thanks

**Comment by ghiscoding** [comment]
Can you provide more info, I don't really understand what you're looking for. Please provide exactly which filter you're using and data sample and/or print screen

**Comment by audrys** [comment]
![renameFilter](https://user-images.githubusercontent.com/3426170/114869186-ff8edb00-9df6-11eb-8c57-1f429859290d.png)

Hi,
Thanks for answer.
Te question is how to rename filter options or add new one
Thanks

**Comment by ghiscoding** [comment]
There's not currently a way to override those, they are set in the Compound Input Filter and depending if the Field Type is number or a string it will use 2 different list of Operators but they are really static lists. If you would like to contribute to the lib and add a way to provide custom list of Operators that's be nice.

https://github.com/ghiscoding/Angular-Slickgrid/blob/c1fdde9e0470604296ff6b331703b08e2981c4ea/src/app/modules/angular-slickgrid/filters/compoundInputFilter.ts#L166-L195

**Comment by ghiscoding** [comment]
BTW, you cannot add any new Custom Operator that won't work and is not allowed because it has to be of type `OperatorString` or `OperatorType` (it's the same list but as a string or an enum). The biggest reason why adding Custom Operator won't work is not just because of the TS Type but mainly because Angular-Slickgrid won't know what to do with it, the lib has its own list of Operators and it knows how to filter because of everything that is the [filter-conditions](/ghiscoding/Angular-Slickgrid/tree/master/src/app/modules/angular-slickgrid/filter-conditions) folder (unless it's a Backend Service then the filtering would not happen in the lib but on the backend side). 

So if it's just to rename the text shown in the Operator dropdown, then it's doable and would require contribution to the lib (as written in previous post). However, if you want Custom Operator that won't be doable.

**Comment by ghiscoding** [comment]
@audrys  
This feature is now shipped and is available through the same code I wrote in previous post. 
See latest [version 2.28.1](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.28.1) release

Cheers ⭐
