### ISSUE TITLE
All records are not getting selected

### ISSUE THREAD

**Issue by Anant1008** [ghiscoding/Angular-Slickgrid#738]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/74755428/115836330-fb853d80-a434-11eb-87c3-73a707f7753a.png)

When we check on 'select all' in slickgrid header, when enableCheckboxSelector option is true in the grid option, all the records are not getting selected across all pages in the grid. Only current page records are getting selected.

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 9.1.0        | 
| Angular-Slickgrid | 2.25.0        | 
| TypeScript        | 3.8.3        | 
| Operating System  | x.y        | 
| NPM/Node/Yarn     | x.y        | 

### Expected Behavior
All the records should get selected across all pages in the grid.

### Current Behavior
Only current page records are getting selected.

**Comment by ghiscoding** [comment]
That is totally normal especially when using a Backend Service (OData/GraphQL), so that cannot and will not ever be supported.
If you're using local pagination, it's also not currently supported. There was an attempt on the SlickGrid core lib in this [PR](https://github.com/6pac/SlickGrid/pull/545) but there were a few issues with and no time to finish it. 
So as it stands, the behavior is that it will select only current page.

Please fill in the issue template properly next time to avoid it being closed by the bot

**Comment by Anant1008** [comment]
So we probably have to write our own logic?
