### ISSUE TITLE
Multi select drop down selection is not persisting if we have autoCommitEdit: true

### ISSUE THREAD

**Issue by johnsdy779** [ghiscoding/Angular-Slickgrid#752]
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 8.x.y        | 
| Angular-Slickgrid   | 2.27.0       | 
| TypeScript              | 3.2.x        | 

### Describe the Bug
https://ghiscoding.github.io/Angular-Slickgrid/#/editor

In above link, I have selected auto Commit option and single click,  because I dont want my select drop-down getting open for descendent cells if I click out side of the table

In this case if in multi-select column i.e. prerequisites column if you select Task 1 and Task 2 and click out side on some other row of table the selection is not persisting.

### Steps to Reproduce
1. Click auto Complete true (for me auto Commit should be true other wise it will open drop down for descendent cells)
2. Select select Task 1 and Task 2 from prerequisites column
3. Click on some other row not on the same row. Selection done for prerequisites column cell is not persisting

### Expected Behavior
Should persists the  prerequisites column cell selection if you click on some other row of table

### Current Behavior
Multi select drop down selection is not persisting if we have autoCommitEdit: true

### Possible Solution
Please provide possible solution for this

### Code Sample
https://ghiscoding.github.io/Angular-Slickgrid/#/editor

This looks a bug for us thats why I am reporting to github

**Comment by ghiscoding** [comment]
hmm I always, and must users do as well, click on the "OK" button at the bottom. I never tried clicking outside and that kinda make sense that it doesn't do anything. I assume this problem is in the 3rd party lib `multiple-select`, if you want to help you can take a look at the file [multiple-select.js](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/assets/lib/multiple-select/multiple-select.js), it's a customized version of that 3rd party lib (for example, I added the "OK" button since that didn't exist in the original lib).

**Comment by ghiscoding** [comment]
That was fixed over a week ago and is now released.
Take a look at the new version [2.29.x](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.29.0)

Cheers ⭐
