### ISSUE TITLE
Slickgrid Tree: Auto Grid-refresh after dataload from DB

### ISSUE THREAD

**Issue by Mad4emno** [ghiscoding/Angular-Slickgrid#805]
Hi, I am trying out the new Slickgrid Tree (Angular-Slickgrid Version 2.18.7) and extended the example 29: Tree Data (from a Hierarchical Dataset).
But I am using Data from a DB which I have to load from the Backend in the first place.

My Question is: 
how can I force the grid to update the rendering of the tree items? 

I just want the data from the backend to show up without any extra click or move on the grid. In the moment I have to click on the row header (which is causing some kind of sorting event I guess) to show the data I got from the backend...

I tried methods like 'this.angularGrid.sortService.sortLocalGridByDefaultSortFieldId()' or 'this.angularGrid.gridService.invalidateHierarchicalDataset(newItems)' after the data arrived in the frontend, but nothing helped :-/
I always have to click on the row header to see the correct tree data...

A hint which method I have to call for refreshing the grid could be enough to help me...

Thanks for any help or advice in advance! :-)

**Comment by ghiscoding** [comment]
1. you should fill the issue form as requested (which is why the Bot closed your issue)
2. you're using a very old version of Angular-Slickgrid and lot of fixes were pushed recently for Tree Data (and I mean a **lot**)
3. just calling `[datasetHierarchical]="datasetHierarchical"` should be enough, internally it's a SETTER and it should call the refresh of the grid if the SETTER is triggered... but again you're using a very old version so that might be the problem. All of the Examples have mock data using JS but in reality we always use a backend server to get the data
4. you should read the [Tree Data - Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Tree-Data-Grid) and if it's missing details then open a [Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions) instead of an Issue.
5. also like the Bot message says, please ask these kind of questions on Stack Overflow where a lot more people can answer questions. 

Final closing... you should upgrade to latest version
