### ISSUE TITLE
Column hide is not working when changing the frozen column data by setOptions

### ISSUE THREAD

**Issue by ranjithitwizard** [ghiscoding/Angular-Slickgrid#835]
## I'm submitting a Bug report
My grid has frozen column. When showing/hiding any frozen column, I need to increment/decrement the `frozenColumn` count by 1. Also the new value should get updated using `setOptions()` which is working perfectly, but the removing the colum from grid is not working.

### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 9.1.1        | 
| Angular-Slickgrid   | 2.21.3      | 
| TypeScript              | 3.8.3        | 

### Describe the Bug

Bug 1: Column hide is not working when changing the frozen column data by setOptions in both **ColumnPicker** and **GridMenu**

Bug 2: Also the Colum Picker(from Header Menu) doesn't trigger the event `onColumnsChanged`

### Steps to Reproduce

1. Set freeze column by any positive number and load the grid
2. Add event handler for `headerMenu.onCommand == 'hide'` ( for ColumnPicker ) with updating the `frozenColumn` number(for eg. decrement by 1)
3. Add event handler for `gridMenu.onColumnsChanged` ( for GridMenu ) with updating the `frozenColumn` number
4. Hide any column using ColumnPicker menu/GridMenu(for eg. decrement by 1)
5. Frozen Column numbers are updating correctly but removing/hiding the column from the grid is not applying.

### Expected Behavior

Column hide should work after the column freeze..
### Code Sample

```
this.frozenColumnCount = 3;

// Hide Column by ColumnPicker(Header Menu) click
gridOptions.headerMenu = {
      onCommand: (e, args) => {
          //event capture when column hide
          if(args.command == 'hide') {
                this.gridObj.setOptions({
                  frozenColumn: this.frozenColumnCount - 1
                });
          }
      }
}, 

// Hide Column by Grid Menu click
gridOptions.gridMenu.onColumnsChanged = (e, args) => {
    console.log('Column selection changed from Grid Menu, visible columns: ', args.columns);
    
    // assume only for hide column to decrement the value by 1
    this.gridObj.setOptions({
      frozenColumn: this.frozenColumnCount - 1
    });
}
```

**Comment by ghiscoding** [comment]
This is expected and happening because Angular-Slickgrid keeps a local reference to its own grid options and if you use `setOptions` directly from SlickGrid then it becomes out of sync with the ones that Angular-Slickgrid keeps. Just don't do that and use other methods that I created for that use case which keeps Angular-Slickgrid in sync, just use [gridService.setPinning(...)](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/common/src/services/grid.service.ts#L98) and also [extensionService.hideColumn(...)](https://github.com/ghiscoding/slickgrid-universal/blob/2abe803340d2dfbe39f77e09492d15c059d807fd/packages/common/src/services/extension.service.ts#L302). You have to keep in mind that this lib is a wrapper of SlickGrid and certain things are on 1 side while other things are on another side and if you use `setOptions` then you are bypassing Angular-Slickgrid and it won't be aware of the change
