### ISSUE TITLE
Getting error while doing TreeData(parent/child)

### ISSUE THREAD

**Issue by vysakhtk886** [ghiscoding/Angular-Slickgrid#861]
## General Topic
Getting error while doing TreeData(parent/child)

### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | 8.2.3        | 
| Angular-Slickgrid | 2.18.7        | 
| TypeScript        | 4.4.2       | 
| Operating System  | windows 7        | 
| NPM/Node/Yarn     | 6.14.4     | 

### Context
while doing tree data formatters.tree   get error like "Property 'tree' does not exist on type" and "Object literal may only specify known properties, and 'enableTreeData' does not exist in type 'GridOption'."

### Expected Behavior
work treedata correctly

### Current Behavior
not working

### Possible Solution
![Capture222](https://user-images.githubusercontent.com/81738337/142871328-676daf8a-e52a-4899-8b9a-e454b3e734f8.PNG)

**Comment by ghiscoding** [comment]
That is correct and is because you're using a very old version `2.18.7` which doesn't have that formatter.
You have 3 options to deal with this:
1. upgrade to latest version 3.x (preferable but that will require some work from your side to upgrade both Angular & Angular-Slickgrid)
2. Upgrade to last 2.x feature version `2.30.4`
3. copy the Formatter to your local project and use that Formatter instead
   - you can [Tree Formatter](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/common/src/formatters/treeFormatter.ts) and you might need the [Constants](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/common/src/constants.ts#L71)

Note: I don't provide support for version 2.x anymore and so you should think about upgrading eventually, there's a few new features in 3.x and the Tree Data got improved a lot (performance & bug fixes) but you'll need to upgrade to Angular 12 as well.

**Comment by vysakhtk886** [comment]
Thank you for your replay,
I upgraded the angular slick grid version 2.30.4 but still not working. There is no option for enable tree data in grid options.
![slickgrid](https://user-images.githubusercontent.com/81738337/142983688-9d89a8f7-5625-42b8-891b-1812d7036025.PNG)

**Comment by ghiscoding** [comment]
your update didn't seem to have gone well, I would suggest to delete your entire `node_modules` folder and reinstall everything and maybe restart your editor after the install.

**Comment by ghiscoding** [comment]
closing since this was answered and is not a problem with the lib itself, I also stopped supporting version 2.x (so please upgrade whenever possible).
