### ISSUE TITLE
Export all records, rather than just what is on displayed page

### ISSUE THREAD

**Issue by twalker1998** [ghiscoding/Angular-Slickgrid#913]
### Export all records, rather than just what is on displayed page

Currently, `angular-slickgrid` only supports exporting the currently viewed page of data. I (and I assume others) have a use case in which, I'd like to display only a subset of data (say, 50) per page in my application, but when exporting to CSV or Excel format, all records from all pages should be exported. It would be nice to have this implemented so I don't have to display all data on a single page by default (my application deals with very large datasets, >1000 records in many cases).

I found [this](https://stackoverflow.com/questions/62384339/required-to-export-all-page-records-in-angular-slickgrid-export-option) question in which @ghiscoding answered that this is by design and it wouldn't be changed. My question is, why? Seems to me that, it would be simple and quite advantageous for many users if the export function looped over the data source, rather than the data view.

### Suggested solution

Export from the data source, rather than the data view of an `angular-slickgrid`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
> My question is, why? Seems to me that, it would be simple and quite advantageous for many users if the export function looped over the data source, rather than the data view.

Well ok, if you think that is so simple then please bring on the Pull Request then...

The thing is that Angular-Slickgrid uses **only** the DataView from SlickGrid, it might be an option in the regular SlickGrid but it's not an option in Angular-Slickgrid. I decided long time ago that because of all the benefit that the SlickGrid DataView brings to the table, it was going to be the default and only way to deal with the data in Angular-Slickgrid. The export loops through that DataView data and uses that to export. I can only bet that rewriting the export to use the raw data would require a lot of code change and time which I don't have. 

However the SO question you pointed to is using Pagination with a Backend API Service and yes it cannot export more than current page and yes that is by design because the Backend Service API uses the DataView to hold only the current page, every time you change page it flushes the data and overwrite with the next page data, exporting the entire dataset would mean to load the entire dataset somewhere, most probably in the DataView but the DataView is already busy with the current page and if you push more data to the DataView then it will affect (break) your current page and that just won't work (so yes it's by design for that reason). Perhaps you could build another Service to get the raw data and save it somewhere, remember that if you have 100,000 rows you will have to save that somewhere before looping through it for the export and I don't think that the Excel Export Service will actually work with that since I heard someone complaining that it wasn't working with large dataset and I think it was because `excel-builder.js` keeps everything in memory too, so it's probably not a good idea. That same person said that the Text Export was working fine though.  

So... If you think that is so simple then please go ahead and bring a pull request, that would have to be in Slickgrid-Universal [Export Service](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/excel-export/src/excelExport.service.ts). From my point of view though, the fact is that I wrote 95% of the code of Angular-Slickgrid, Slickgrid-Universal and brought a lot of PRs into SlickGrid core lib as well but the thing is that I barely receive any PRs and contributions (I did get a few PRs for OData though) and I decided that I wasn't going to expand more than what the current export, SlickGrid itself never had export and I built that myself from scratch, but the fact is that I'm alone, I'm tired and I barely receive any contributions and I'm tired of working for free. I believe that I have achieved everything that I wanted with the lib and my focus is currently on something else, that doesn't mean that the project is dead but as far as I know all the features that I wanted to do were achieved.

**Comment by twalker1998** [comment]
I apologize if that came across as snarky, I didn't mean for it to, and was genuinely just asking why that is the case. I'll look more into it and see if I can't implement that and submit a PR if I can figure it out. Thanks for the explanation, that will be quite helpful in that endeavor (as I am also using the pagination with a backend API service). Completely understand that you don't have enough time to handle it yourself :)

**Comment by twalker1998** [comment]
As a token of good favor, would like to say that I love what you've done with this library and it's been extremely useful for my use cases. Just don't want to see it die as I plan on using it for quite a long time.

**Comment by ghiscoding** [comment]
I also didn't want to be too harsh either, I just think it might be a bit bigger than you imagined and I was just saying in summary that it's hard to be a single maintainer of a project like this hehe...  Nonetheless I'm still open to suggestions and I am still a talkable person 😉 I'm also still maintaining it, mostly dependency updates lately, just a little less focus 😁 

Cheers and thanks for the good words

Side note, nothing can be worst than this kind of [request](https://github.com/ghiscoding/Angular-Slickgrid/issues/513), I just hate it when some users think I work for them... I just don't reply in these cases lol. 

I also had long [discussions](https://github.com/ghiscoding/Angular-Slickgrid/discussions/763) that I was expecting a PR to eventually come my way but I'm still waiting... hence why I replied the way I did, that's a bit of the background. Feel free to reach out again, it might be better as a Discussion though. 

Cheers
