### ISSUE TITLE
Feature request - Explicitly save "hidden" columns in grid state

### ISSUE THREAD

**Issue by waltzonice** [ghiscoding/Angular-Slickgrid#966]
### Clear and concise description of the problem

Currently, the hidden columns are implied if they are omitted in the columns array in the grid state (as explained [here](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-State-&-Preset#how-to-load-grid-with-certain-columns-preset-example-hide-certain-columns-on-load)). This approach works fine if the column definition is identical when applying the preset. The problem is if the column definition contains new columns, those columns will be omitted because they will not be in the previously saved state and therefore will not be shown to the user by default.

### Suggested solution

Include all columns in the grid state (hidden and unhidden) and explicitly include a "hidden=true" if the column is hidden. This would allow any new columns in the column definition to be shown if they were not in the columns from the saved state. This would also allow any sorting and filters that were applied to the column to be saved, so that they can be applied when the column becomes unhidden.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
The concept of the hidden columns, which you referred from the Wiki, comes from the core SlickGrid implementation, this cannot be modified easily in Angular-Slickgrid. Internally Angular-Slickgrid calls `slickGrid.setColumns()` and that format is defined by SlickGrid and I cannot change it which is as you found out that any omitted columns will be hidden. 

If you follow the suggested way of adding new columns, as per Angular-Slickgrid [Example 3](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) or Slickgrid-Universal [Example 7](https://ghiscoding.github.io/slickgrid-universal/#/example07) then the Grid State should be updated accordingly. If however you try to call `slickGrid.setColumns()` yourself then that would bypass and conflict with Angular-Slickgrid Grid State

So I don't think I can do anything better since the lib is restricted to the SlickGrid implementation and going in a different would require way too many changes in both libs

**Comment by waltzonice** [comment]
Thank you for the explanation. In the case where the column definition is retrieved dynamically, there would be no way to know which are the "new" columns, hence the problem. But I certainly understand if the design comes from SlickGrid and would be too difficult to change.

**Comment by ghiscoding** [comment]
Yeah that would have to be tracked from your side it shouldn't be too hard to do comparison and you should be able to do that by tracking changes anytime the Grid State column list changes, it's much easier than having the lib do it for you which would require way too many changes as I mentioned. So I'll close this as "won't fix", thanks for using the lib ⭐ 

You can try something along these lines (untested)
```html
(onGridStateServiceChanged)="gridStateChanged($event)"
```
```ts
gridStateChanged(gridState: GridStateChange) {
   if (gridStateChange.change.type === GridStateType.columns) {
      console.log('Columns changed, new columns are', gridState.gridState.columns);
      // keep a ref of previous columns and compare with new columns
    }
}
```

Cheers and happy coding
